### DISCUSSION TITLE
How to mutate a rule in a stylesheet.

### DISCUSSION THREAD

**Discussion by paulm17** [parcel-bundler/lightningcss#622] [Q&A]
Hello.  I'm still very new to Rust and although I can now traverse the StyleRule struct.  I'm having great difficulty in mutating it using the visitor trait.

Here's my use case:

```css
.menuSlider {
  outline: rem(2px) solid var(--raikou-primary-color-filled);
}
```

I'm wanting to swap out rem(2px) with the following:

```css
.menuSlider {
  outline: calc(0.125rem * var(--raikou-scale)) solid var(--raikou-primary-color-filled);
}
```

I'll give a basic example with hardcoded values, just to bring about the problem I'm having...

Note: I do have a function to retrieve the 2px from the rem function and then make the calculation.  But I am omitting this in favour of brevity. 

```rust
fn visit_rule(&mut self, rule: &mut CssRule) -> Result<(), Self::Error> {
  if let CssRule::Style(style_rule) = rule {
    let css = format!(
      "{}: {};",
      "outline",
      "calc(0.125rem * var(--raikou-scale)) solid var(--raikou-primary-color-filled)"
    );

    let new_declaration = DeclarationBlock::parse_string(
      &css,
      ParserOptions::default()
    ).unwrap();

    style_rule.declarations = new_declaration;
  }
  
  Ok(())
}
```

The issue is &css is not being dropped in the parse_string method of the trait DeclarationBlock.

```
`css` does not live long enough
borrowed value does not live long enough
```

At the end of the function bracket, if I hover over:

```
`css` dropped here while still borrowed
```

What's the solution?  When I go through the source many functions have ticks or (long lives?).  I am unsure how to resolve this issue.  Or perhaps I am not using the library as intended?

Any advice would be most welcome!  

Thanks!
