### DISCUSSION TITLE
How to discard a media query along with its content?

### DISCUSSION THREAD

**Discussion by Stigjb** [parcel-bundler/lightningcss#679] [Q&A] [answered]
I want to discard all `@media print` definitions from a CSS file. For example, given:

```css
  .foo { width: 100px; }
  @media print {
    .bar { width: 50mm; }
  }
  .baz { width: 200px; }
```

I want the result to be `.foo{width:100px}.baz{width:200px}`.

I have experimented with visitors, and successfully identified the print queries with a `MediaQuery` visitor. However, if I return `[]` from the visitor, the properties within are just unwrapped. In fact, both the `MediaQuery` and `MediaQueryExit` visitors seem to come before any of the contents.

Is there a way to do this?
