### DISCUSSION TITLE
Pseudo element content alt text support OR custom transform help

### DISCUSSION THREAD

**Discussion by jossmac** [parcel-bundler/lightningcss#756] [Ideas]
How would you implement a custom transform for `content` [alternative text](https://developer.mozilla.org/en-US/docs/Web/CSS/content#alternative_text)?

```css
/* input */
.class-name::after {
  content: "chevron_right" / "";
}

/* desired output */
.class-name::after {
  content: "chevron_right" / "";
}
@supports not (content: "x" / "y") {
  .class-name::after {
    alt: "";
    content: "chevron_right";
  }
}
```

Ideally this would be built into the library and respond to the `targets` option. Failing that, I'd really appreciate help implementing a robust custom transform.
