### DISCUSSION TITLE
How to prevent formatting？

### DISCUSSION THREAD

**Discussion by 1714080902120** [parcel-bundler/lightningcss#933] [Q&A]
I replaced postcss with lightningcss, but I found that one of my plugins didn't work, which relied on the format of the code, such as:
```css
// default code
body { --test:a,b,c; }

// postcss keep original, work
body { --test:a,b,c; }
// lightningcss default perform don't work
body { 
  --test: a, b, c;
}
```
How to solve it?
