### ISSUE TITLE
The conversion of calc() does not take into account the valid range of the property value

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#1000]
## Input

```css
.foo {
  width: calc(5px - 10px);
}
```

## Lightningcss output

```css
.foo {
  width: -5px;
}
```

## Expected

```css
.foo {
  width: 0px;
}
```

## Specs

https://drafts.csswg.org/css-values-4/#example-ec14dee2

> Note however that [width: -5px](https://drafts.csswg.org/css-sizing-3/#propdef-width) is not equivalent to width: calc(-5px)! Out-of-range values outside [calc()](https://drafts.csswg.org/css-values-4/#funcdef-calc) are syntactically invalid, and cause the entire declaration to be dropped.

It is very **unsafe** to do unfolding calculations for calc(), we should add an option to turn it off.
