### ISSUE TITLE
Bug: normal selector sandwiched between nested selectors produces invalid CSS

### ISSUE THREAD

**Issue by decorator-factory** [parcel-bundler/lightningcss#1002]
Tested on the playground (https://lightningcss.dev/playground/index.html) with target being Firefox 139.0 and the package version being `1.30.1`.

Input CSS:
```css
.foo {
    &.bar { color: red; }
    border-color: blue;
    &:hover { background: green; }
}
```
Output CSS:
```css
.foo{&.bar{color:red}border-color:#00f&:hover{background:green}}
```
Expected CSS (`;` needed before the `&:hover`):
```css
.foo{&.bar{color:red}border-color:#00f;&:hover{background:green}}
```
