### ISSUE TITLE
Missing semicolon after variable defined between selectors

### ISSUE THREAD

**Issue by gejgalis** [parcel-bundler/lightningcss#1003]
When `--some-var` is placed between selectors, then minifier omits the semicolon.

![Image](https://github.com/user-attachments/assets/da793f9e-12d5-4501-b999-5e0f6db4f4e4)

```css
.Foo {
  color: red;

  .Bar {
    color: blue;
  }

  --some-var: 100%;  /* <- this semicolon is missing */

  .Baz {
    color: green;
  }
}
```

[Playground](
https://lightningcss.dev/playground/#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A8847360%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.Foo%20%7B%5Cn%20%20color%3A%20red%3B%5Cn%5Cn%20%20.Bar%20%7B%5Cn%20%20%20%20color%3A%20blue%3B%5Cn%20%20%7D%5Cn%5Cn%20%20--some-var%3A%20100%25%3B%5Cn%5Cn%20%20.Baz%20%7B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by StratusFearMe21** [comment]
This is still an issue

**Comment by StratusFearMe21** [comment]
This problem also seems to be with nesting, not specifically with variables

**Comment by yihui** [comment]
I just ran into the same issue. [Playground](https://lightningcss.dev/playground/#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A1%2C%22source%22%3A%22p%20%7B%5Cn%20%20%26%20*%20%7B%5Cn%20%20%20%20margin%3A%200%3B%5Cn%20%20%7D%5Cn%20%20margin%3A%201em%3B%5Cn%20%20%26%20%3Ais(a)%20%7B%5Cn%20%20%20%20width%3A%202em%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

```css
p {
  & * {
    margin: 0;
  }
  margin: 1em;
  & :is(a) {
    width: 2em;
  }
}
```

Output:

```css
p{& *{margin:0}margin:1em& :is(a){width:2em}}
```

The semicolon was missing before the second `&`.
