### ISSUE TITLE
Support `::grammar-error` and `::spelling-error`

### ISSUE THREAD

**Issue by jakubriedl** [parcel-bundler/lightningcss#1021]
[::grammar-error](https://developer.mozilla.org/en-US/docs/Web/CSS/::grammar-error) and [::spelling-error](https://developer.mozilla.org/en-US/docs/Web/CSS/::spelling-error) are reasonably well supported features in all modern browsers except Firefox but not yet supported in lightningcss and showing error when build. Full example with reproduction can be found in [og issue](https://github.com/vercel/next.js/issues/81035) raised in Nextjs repo

This code should work:
```css
::grammar-error,
::spelling-error {
    text-decoration: 2px underline rgba(255, 30, 30, 0.5);
    text-decoration-style: wavy;
}
```

Related links
- https://github.com/parcel-bundler/lightningcss/issues/888#issuecomment-2610307058
- https://github.com/vercel/next.js/issues/81035
