### ISSUE TITLE
Overwriting fallbacks are generated when hand picked values already existed

### ISSUE THREAD

**Issue by argyleink** [parcel-bundler/lightningcss#109]
[parcel-css repro link](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%2F*%20hand%20picked%20fallbacks%2C%20dont%20want%20generated%20ones%5Cn%20%20%20parcel's%20generated%20fallbacks%20overwrite%20them%5Cn%20*%2F%5Cn%3Awhere(html)%20%7B%5Cn%20%20--link%3A%20%234263eb%3B%5Cn%20%20--link-visited%3A%20%23ae3ec9%3B%5Cn%5Cn%20%20%40media%20(dynamic-range%3A%20high)%20%7B%5Cn%20%20%20%20--link%3A%20color(display-p3%200%20.5%201)%3B%5Cn%20%20%20%20--link-visited%3A%20color(display-p3%20.6%20.2%201)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%2F*%20alt%20attempt%20*%2F%5Cn%3Awhere(html)%20%7B%5Cn%20%20--link%3A%20%234263eb%3B%5Cn%20%20--link-visited%3A%20%23ae3ec9%3B%5Cn%5Cn%20%20%40supports%20(color%3A%20lab(0%25%200%200))%20%7B%5Cn%20%20%20%20--link%3A%20color(display-p3%200%20.5%201)%3B%5Cn%20%20%20%20--link-visited%3A%20color(display-p3%20.6%20.2%201)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%2F*%20letting%20parcel%20do%20it's%20thing%20*%2F%5Cn%3Awhere(html)%20%7B%5Cn%20%20--link%3A%20color(display-p3%200%20.5%201)%3B%5Cn%20%20--link-visited%3A%20color(display-p3%20.6%20.2%201)%3B%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%7D)

curious how i can work around this? i'm going more of an "upgrade" path and picking both colors.

**Comment by romainmenke** [comment]
I haven't considered this case either in `postcss-preset-env`

```css
:where(html) {
  --link: #4263eb;
  --link-visited: #ae3ec9;

  @media (dynamic-range: high) {
    --link: color(display-p3 0 .5 1);
    --link-visited: color(display-p3 .6 .2 1);
  }
}
```

We do try to detect these types of manual fallbacks in recent plugins :

```css
.foo {
  color: #4263eb;
  color: color(display-p3 0 .5 1); /* will not be transformed */
}
```

I think this works :

```css
:where(html) {
  --link: #4263eb;
  --link-visited: #ae3ec9;
  --link-hdr: color(display-p3 0 .5 1);
  --link-visited-hdr: color(display-p3 .6 .2 1);

  @media (dynamic-range: high) {
    --link: var(--link-hdr);
    --link-visited: var(--link-visited);
  }
}
```

Curious if there is a better way to handle this pattern :)

**Comment by devongovett** [comment]
Not sure if we could handle this for the `dynamic-range` media query, because that is already supported in Chrome whereas P3 colors are not. Perhaps we could detect `@supports` queries though.

**Comment by argyleink** [comment]
I tried switching it to a supports query to see if it'd "do less" which is did a little, but still reproduced the overwriting props

**Comment by devongovett** [comment]
Yeah sorry, I meant we could detect it in the future, not that we do currently.

**Comment by deardaniel** [comment]
I ran into a similar issue where I had multiple `background-image` properties: one with `image-set` and one as a fallback with a simple `url()` and was surprised when I saw my fallback was removed.

https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.my-class%20%7B%5Cn%20%20background-image%3A%20url('test.png')%3B%5Cn%20%20background-image%3A%20image-set(url('test.png')%2C%20url('test%402x.png')%202x%2C%20url('test%403x.png')%203x)%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

**Comment by maxnordlund** [comment]
> I ran into a similar issue where I had multiple `background-image` properties: one with `image-set` and one as a fallback with a simple `url()` and was surprised when I saw my fallback was removed.
> 
> [repro link](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.my-class%20%7B%5Cn%20%20background-image%3A%20url('test.png')%3B%5Cn%20%20background-image%3A%20image-set(url('test.png')%2C%20url('test%402x.png')%202x%2C%20url('test%403x.png')%203x)%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
> 
> In [the docs](https://github.com/parcel-bundler/website/blob/6c18f5b493ba3b468fb50ae934d7881f7e852dbb/src/languages/css.md#vendor-prefixing) there is a link to [this page](https://developer.mozilla.org/en-US/docs/web/css/image/image-set) on `image-set` which suggests multiple `background-image` properties are set for backwards compatibility, and it does not seem like this works with parcel-css.

This bit me just now. I'm not sure if it's the same issue, so I'll open a new one specific to `image-set`.

**Comment by devongovett** [comment]
Working on this one. Basically it'll look at each value and determine if it is supported by all of your browser targets. If so, then it will drop previously declared fallbacks, otherwise it'll preserve them. This will let you manually set different fallback values than Lightning CSS would generate.

```css
.foo {
  background-color: #4263eb;
  background-color: color(display-p3 0 .5 1);
}
```

In the above example, `#4263eb` would be preserved rather than overwritten with `#0085f8`.

There are some interesting edge cases though. For example, how should vendor prefixing play with fallbacks?

```css
.foo {
  background: url(foo.png);
  background: image-set("foo.png" 2x, "bar.png" 1x);
}
```

Is this declaring that the fallback should be `url(foo.png)` when `image-set` isn't supported, or when `-webkit-image-set` isn't supported? Should Lightning CSS still insert another declaration for `-webkit-image-set` here or not?

Another case:

```css
.foo {
  background: red;
  background: linear-gradient(lch(50% 132 50), lch(50% 130 150));
}
```

Should Lightning CSS add a `-webkit-linear-gradient` as well when needed? If it did so, it would also need to convert the LCH colors to RGB. This is in effect the same scenario as the first one we wanted to avoid - overwriting the manually chosen fallback value. In this case the fallback isn't a gradient, so the answer is less obvious.

I need some opinions on this. Please let me know your thoughts!
