### ISSUE TITLE
Wrong urls after bundling

### ISSUE THREAD

**Issue by dmail** [parcel-bundler/lightningcss#181]
Hello, there is an issue relative to urls when parcel bundle css files together.
Urls found in files that gets bundled should be updated somehow because the following happens for now:

elements.css
```css
@import "./fire/fire.css";
@import "./water/water.css";
```

fire/fire.css
```css
.fire {
  background: url("./logo.png");
}
```

water/water.css
```css
.water {
  background: url("./logo.png");
}
```

Actual output generated by parcel

```css
.fire, .water {
  background: url(./logo.png);
}
```

Expected output

```css
.fire {
  background: url(./fire/logo.png);
}
.water{
  background: url(./water/logo.png);
}
```

<details>
  <summary>Code used to run parcel css bundler</summary>

```js
import { createRequire } from "node:module"
import { fileURLToPath } from "node:url"

const require = createRequire(import.meta.url)

const { bundle } = require("@parcel/css")

const { code } = await bundle({
  filename: fileURLToPath(new URL("./elements.css", import.meta.url)),
  minify: false,
})
console.log(String(code))
```

</details>
