### ISSUE TITLE
Animation with CSS variables transforms incorrect

### ISSUE THREAD

**Issue by Megoos** [parcel-bundler/lightningcss#194]
Hello!

If you just try:
```
.container {
  --duration: 1.8s;
  animation: rotate var(--duration) linear infinite;
}

@keyframes rotate {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(-360deg);
  }
}
```

[on the Playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Atrue%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.container%20%7B%5Cn%20%20--duration%3A%201.8s%3B%5Cn%20%20animation%3A%20rotate%20var(--duration)%20linear%20infinite%3B%5Cn%7D%5Cn%5Cn%40keyframes%20rotate%20%7B%5Cn%20%20from%20%7B%5Cn%20%20%20%20transform%3A%20rotate(0deg)%3B%5Cn%20%20%7D%5Cn%20%20to%20%7B%5Cn%20%20%20%20transform%3A%20rotate(-360deg)%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) it will result to:

```
.EgL3uq_container {
  --duration: 1.8s;
  animation: rotate var(--duration) linear infinite
}

@keyframes EgL3uq_rotate {
  0% {
    transform: rotate(0deg)
  }
  to {
    transform: rotate(-360deg)
  }
}
```

As you can see in the animation CSS property, the name of animation is without hash. If you remove the css variable, the transformation will succeed.

**Comment by devongovett** [comment]
I'd recommend using the longhand properties for this. Either:

```css
.foo {
  animation: var(--duration) linear infinite;
  animation-name: rotate;
}
```

or:

```css
.foo {
  animation: rotate linear infinite;
  animation-duration: var(--duration);
}
```
