### ISSUE TITLE
Only adjacent rules are merged

### ISSUE THREAD

**Issue by binyamin** [parcel-bundler/lightningcss#225]
### Summary
Rules which target the same _selector_, or include the same _declaration_, are only merged when they are adjacent.

### Example
The following code has three rules for `body`, and one rule for `h1` in between them. When I run `parcel bundle style.css`, only two `body` rules are merged.

**Input**
```css
body {
    color: red;
}

body {
    background-color: blue;
}

h1 {
    font-weight: normal;
}

body {
    margin: 0;
}
```

**Output**
```css
body{color:red;background-color:#00f}h1{font-weight:400}body{margin:0}
```

**Comment by binyamin** [comment]
@devongovett Understood. However, Parcel has extensive knowledge of the CSS. I specifically chose a case where they're all different selectors.

**Comment by devongovett** [comment]
That definitely limits the usefulness of this though. It means for any rule, you'd have to walk backwards through all previous rules, and none of them can have any overlap between any of their properties. Doesn't seem like it would happen often in practice.

**Comment by ArnaudBarre** [comment]
I think there are a lot of projects out there hat uses Tailwind, and then add few more defaults on html or body

**Comment by naruaway** [comment]
@devongovett Can we add new configuration option to declare that "these selectors will never be used in the same element"? It will be basically the same as [csso's "scopes" feature](https://github.com/css/csso#scopes).
This feature will be useful to aggressively merge styles generated by things like zero-runtime CSS-in-JS like the following:
```css
.css-xyzabc {
  color: red;
}

.css-o3z7bc {
  color: blue;
}

.css-kyzkcc {
  color: red;
}

```

Should become:
```css
.css-xyzabc,.css-kyzkcc  {
  color: red;
}

.css-o3z7bc {
  color: blue;
}
```

We (human) know that these classes will never overlap on the same element but there is no way to tell this fact to lightningcss. I see this as "dual" form of atomic CSS ("atomic selector"?)
