### ISSUE TITLE
Bundled CSS modules (1.14.0)

### ISSUE THREAD

**Issue by joelmoss** [parcel-bundler/lightningcss#273]
Can you clarify what this actually means please?

> Dependencies in CSS modules are now also bundled. For example, the composes property allows you to reference another file. These will now be bundled, and the resolved class name will be included in the output JSON as well.

I was expecting "bundling" to mean that the code from a dependency is included in the output.

As an example, I have these two source files:

```css
/* ./styles1.module.css */
.firstClass {
  composes: secondClass from './styles2.module.css';
  font-size: 2px;
}
```

```css
/* ./styles2.module.css */
.secondClass {
  color: purple;
}
```

Then with the CLI:

```
bin/lightningcss --css-modules --targets '>= 0.25%' test/internal/lib/styles1.module.css
```

I get the output:

```json
{
  "code": ".KfDXoG_firstClass {\n  font-size: 2px;\n}\n",
  "exports": {
    "firstClass": {
      "composes": [
        {
          "name": "secondClass",
          "specifier": "./styles2.module.css",
          "type": "dependency"
        }
      ],
      "isReferenced": false,
      "name": "KfDXoG_firstClass"
    }
  }
}
```

So while the dependency (`secondClass` from "./styles2.module.css") is registered, I'm not seeing anything extra that is bundled.

Apologies if I'm not understanding this right, but either way, some clarification on this would be awesome. thx!
