### ISSUE TITLE
Should preserve CSS content Numeric entities

### ISSUE THREAD

**Issue by Chastrlove** [parcel-bundler/lightningcss#274]
It should perserve the content code, rather than compile the Numeric entities to the Symbol

[reproduce link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%5Cn.foo%20%7B%5Cn%20%20%26%3A%3Aafter%20%7B%5Cn%20%20%20%20content%3A%5C%22%5C%5C205f%5C%22%3B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
input:
```css
.foo {
  &::after {
    content:"\205f";
    color: green;
  }
}
```

output:
```css
.foo:after {
  content: " ";
  color: green;
}

}
```

expected:
```css
.foo:after {
  content: "\205f";
  color: green;
}
```
