### ISSUE TITLE
Only one CSS-wide keywords can exist in the property value

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#287]
## Invalid value

Should throw an error, but it doesn't now.

```css
.Invalid {
	animation-name: default, two;
	animation-name: one, initial;
	animation-name: one, inherit;
	animation-name: one, unset;
	animation-name: revert, three;
	animation-name: revert-layer, four;
	animation-name: "foo", unset;
	animation-name: unset, "foo";
}
```

## Valid value

```css
.Valid {
	animation-name: none, none;
	animation-name: one, none;
	animation-name: "foo", none;
	animation-name: none, "foo";
}
```

## [csstree](https://csstree.github.io/docs/validator.html) output

```bash
 syntax: [ none | <keyframes-name> ]#
  animation-name: "foo",unset
  ----------------------^
```

Theoretically, any property that supports multiple values, except for the `animation-name` property, needs to be handled this way. For details, see: https://github.com/web-platform-tests/wpt/commit/4f82d323fdb6dd39c1370bd61c7252667994d6bc
