### ISSUE TITLE
CSS transform optimisation breaks animation

### ISSUE THREAD

**Issue by shish** [parcel-bundler/lightningcss#288]
# 🐛 bug report

I'm animating some things falling down the screen and rotating, but my code:
```
        @keyframes rain {
            0% {transform: translateY(0vh) rotate(0deg);}
            100% {transform: translateY(120vh) rotate(360deg);}
        }
```
gets optimised into:
```
        @keyframes rain {
            0% {transform: matrix(1, 0, 0, 1, 0, 0);}
            100% {transform: translateY(120vh) rotate(360deg);}
        }
```

`matrix(1, 0, 0, 1, 0, 0)` is mathematically equivalent to `translate(0)+rotate(0)`... but when we're using keyframe animation, each of the keyframes needs to manipulate the same properties - we can animate from rotate to rotate, but can't animate from matrix to rotate...

Notably this only happens with `parcel build`, not `parcel run`

## 🤔 Expected Behavior

Leave transforms alone if they're being animated

## 😯 Current Behavior

one transform is optimised into a matrix, the other is left alone

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0 |

**Comment by josip** [comment]
I'm having the same issue, my source SCSS:

```css
@keyframes saveArticle {
  from {
    transform-origin: 50% 1400px;
    transform: translateY(0) translateX (0) rotateX(0) scale(1);
  }

  to {
    transform-origin: 50% 100%;
    transform: translateY(-600px) translateX(50%) rotateX(-30deg) scale(0);
  }
}
```

gets converted to this (only in production builds):

```css
@keyframes saveArticle {
    0% {
        transform-origin: 50% 1400px;
        transform: matrix(1, 0, 0, 1, 0, 0)
    }

    to {
        transform-origin: 50% 100%;
        transform: translateY(-600px)translate(50%)rotateX(-30deg)scale(0)
    }
}
```

which breaks the animation.

**Comment by aminomancer** [comment]
Did either of you find a generic workaround for this? Here's the nightmare I'm dealing with...

```css
@keyframes miniLoader-1 {
  0% {
    transform: translateZ(0) scale(0);
    opacity: 1;
  }
  to {
    transform: translateZ(0) scale(1.5);
    opacity: 0;
  }
}
@keyframes miniLoader-2 {
  0% {
    transform: translateZ(0) scale(0);
    opacity: 1;
  }
  to {
    transform: translateZ(0) scale(1);
    opacity: 0;
  }
}
```

into

```css
@keyframes g5nwzq_miniLoader-1 {
  0% {
    opacity: 1;
    transform: matrix(0, 0, 0, 0, 0, 0);
  }
  to {
    opacity: 0;
    transform: scale(1.5);
  }
}
@keyframes g5nwzq_miniLoader-2 {
  0% {
    opacity: 1;
    transform: matrix(0, 0, 0, 0, 0, 0);
  }
  to {
    opacity: 0;
    transform: matrix(1, 0, 0, 1, 0, 0);
  }
}
```

As far as I can tell, I don't really have the option to use degrees for this.
