### ISSUE TITLE
[css-minifier] Don't remove the old browser fallback

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#292]
This issue come from: https://github.com/cssnano/cssnano/issues/1163

```css
.my-class {
  margin-right: 22px;
  margin-right: max(4%, 22px);
}
```

## Output

```css
.my-class {
  margin-right: max(4%, 22px);
}
```

## Expected

```css
.my-class {
  margin-right: 22px;
  margin-right: max(4%, 22px);
}
```
