### ISSUE TITLE
CSS linear-gradient can be omitted when the angle is 0

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#298]
`0` and `0deg` should use the same processing.

## Input
```css
h1 {
    background: linear-gradient(0, red 0%, red 50%, #121 50%, #121 100%)
}
```

## Expected

```css
h1{background:linear-gradient(#121 0% 50%,red 50% 100%)}
```

[playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22h1%20%7B%5Cn%20%20%20%20background%3A%20linear-gradient(0%2C%20red%200%25%2C%20red%2050%25%2C%20%23121%2050%25%2C%20%23121%20100%25)%5Cn%7D%5Cn%5Cn%5Cn.foo%20%7B%5Cn%20%20%20%20background-image%3A%20linear-gradient(0deg%2C%20red%200%25%2C%20red%2050%25%2C%20%23121%2050%25%2C%20%23121%20100%25)%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
