### ISSUE TITLE
[css-minifier] the declaration in `@supports` needs to be compressed

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#301]
# Input

```css
@supports (new-property: 0px) {
    body {
        background: green;
    }
}
```

## Output

```css
@supports (  new-property:  0px  ){body{background:green}}
```

##

Please note that the `0px` here should not be compressed to `0`, the original intent of the CSS author needs to be maintained here.

```css
@supports(new-property:0px){body{background:green}}
```
