### ISSUE TITLE
[css-minifier] colors in CSS custom properties are not compressed

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#303]
## Input

```css
:root {
    --primary-dark: lightblue;
    --white: white;
    --foo: #FFFFFF;
}
```

## Output

```css
:root{--primary-dark:lightblue;--white:white;--foo:#fff}
```

**Comment by yisibl** [comment]
I think it is possible to detect if the variable is referenced by a color related property and it can be safely compressed.

**Comment by devongovett** [comment]
Not if it's in a different CSS file, or referenced from JS.

**Comment by yisibl** [comment]
> Not if it's in a different CSS file, or referenced from JS. 

This situation is indeed not safe.

Thinking further, what if it was defined by `@property`?

```css
@property ----primary-dark {
  syntax: "<color>";
  inherits: false;
  initial-value: #000;
}
```
