### ISSUE TITLE
`infinite` keyword in `@media` range context

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#314]
_here again with obscure CSS_

```css
@media (infinite > resolution) {
  .color {
     color: red;
  }
}

@media (resolution < infinite) {
  .color {
     color: green;
  }
}
```

becomes :

```css
@media (min-infinite: resolution) {
  .color {
    color: red;
  }
}

@media (max-resolution: infinite) {
  .color {
    color: green;
  }
}

```

-----

https://www.w3.org/TR/mediaqueries-5/#resolution

`resolution` is the only feature (that I could spot) that has a `range` type and allows keywords.

This implies that it is ambiguous without detecting `infinite` as a keyword that maps to a value instead of a feature name.

I couldn't find a browser that implements `infinite`.
Also didn't immediately spot a relevant WPT test here : https://wpt.fyi/results/css?label=master&label=experimental&aligned&view=subtest&q=resolution
But haven't done a search through the actual WPT repo.
