### ISSUE TITLE
More control over CSS modules dashed-idents naming

### ISSUE THREAD

**Issue by jacobrask** [parcel-bundler/lightningcss#315]
In our design system we have a public API consisting of class names and CSS variables. We also have some CSS variables that we consider implementation details that we don't want to leak to consumers, and thus want to hash/rename.

Right now if we set a pattern like `[hash]_[local]` this will apply to both class names and CSS variables.

For example

```css
:root {
  --_color-blue: blue;
  --color-foreground-action: var(--_color-blue);
}
a {
  color: var(--color-foreground-action);
}
```

I want the `--_color-blue` variable to be mangled with a hash. There are other more practical use cases like controlling values with `data-` attributes without presenting the CSS variable as a public API.

We currently have a csstree transform mangling variables prefixed with `_`, which achieves what we want but is not a very obvious syntax.

Doing the following and mangling all non-global variables would be a better syntax, but with lightningcss it would currently also add hashes to the class name unless we specify `:global` on every single selector.

```
:root {
  --color-blue: blue;
  --color-foreground-action: var(--color-blue);
}
a {
  color: var(--color-foreground-action from global);
}
```
