### ISSUE TITLE
[Feature request] Merge directly nested media queries when minifying

### ISSUE THREAD

**Issue by ArnaudBarre** [parcel-bundler/lightningcss#319]
With the new release of Tailwind, I think it would happen a lot more.
Example from the release note `min-[712px]:max-[877px]:right-16`: 
```css
@media (min-width: 712px) {
  @media (max-width: 877px) {
    .min-\[712px\]\:max-\[877px\]\:right-16 {
      right: 4rem;
    }
  }
}
```

[playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%40media%20(min-width%3A%20712px)%20%7B%5Cn%20%20%40media%20(max-width%3A%20877px)%20%7B%5Cn%20%20%20%20.min-%5C%5C%5B712px%5C%5C%5D%5C%5C%3Amax-%5C%5C%5B877px%5C%5C%5D%5C%5C%3Aright-16%20%7B%5Cn%20%20%20%20%20%20right%3A%204rem%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
