### ISSUE TITLE
Media query range contexts are sometimes incorrectly downgraded

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#320]
```css
@media screen and (not (200px <= width < 500px)) {
	html {
		background-color: green;
	}
}

@media screen and (not (min-width: 200px) and (max-width: 499.999px)) {
	html {
		background-color: purple;
	}
}
```

I would expect html background color to be `purple` but it is `green`.

When adding `not` before a media feature with a range context the result is a list with `not` and `and` on the same level. `not (min-width: 200px) and (max-width: 499.999px)`

This is not allowed by the specification : https://www.w3.org/TR/mediaqueries-5/#media-conditions

correct transform :

```css
@media screen and (not ((min-width: 200px) and (max-width: 499.999px))) {
	html {
		background-color: purple;
	}
}
```

**Comment by LeoniePhiline** [comment]
The parens around the [`<media-not>`](https://www.w3.org/TR/mediaqueries-5/#typedef-media-not) are even non-standard, as the root-level [<media-condition-without-or>](https://www.w3.org/TR/mediaqueries-5/#typedef-media-condition-without-or) uses no parens. (Only the [<media-in-parens>](https://www.w3.org/TR/mediaqueries-5/#typedef-media-in-parens) inside it.)

Correct would be:

```css
@media screen and not ((min-width: 200px) and (max-width: 499.999px)) {
	html {
		background-color: purple;
	}
}
```

**Comment by romainmenke** [comment]
Both of these work just fine and both are standard :

```css
@media screen and not ((min-width: 200px) and (max-width: 499.999px)) {
	html {
		background-color: purple;
	}
}

@media screen and (not ((min-width: 200px) and (max-width: 499.999px))) {
	html {
		background-color: hotpink;
	}
}
```

The grammar is recursive.
- `<media-in-parens>` can contain a `<media-condition>`
- `<media-condition>` can contain a `<media-not>`
- `<media-condition>` can contain a `<media-in-parens>`

But you can not mix `and` and `not` at the same level.
