### ISSUE TITLE
Animation property broken when using partial shorthand

### ISSUE THREAD

**Issue by AaronAsAChimp** [parcel-bundler/lightningcss#337]
When using a partial shorthand for the animation property, lightningcss replaces the value with none.

Expected behavior, the following is unmodified:

```css
.foo {
  animation: infinite;
}
```

Actual behavior, the property value becomes "none": 

```css
.foo {
  animation: none;
}
```
When all properties are specified it behaves correctly:

```css
.foo {
  animation: 3s ease-in 1s infinite reverse both running slidein;
}
```

[Link to playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22firefox%22%3A6946816%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20animation%3A%20infinite%3B%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by piotr-cz** [comment]
This bug breaks [UIkit](http://getuikit.com/), which doesn't define animation name in the animation shorthand here: https://github.com/uikit/uikit/blob/v3.25.20/src/less/components/animation.less#L43

as a result, this
```css
[class*="uk-animation-"] { animation: 0.5s ease-out both; }
```

is compiled by Lightning CSS to
```css
[class*="uk-animation-"] { animation: none; }
```

workaround is to define properties manually:
```css
[class*="uk-animation-"] {
  animation-duration: 0.5s;
  animation-timing-function: ease-out;
  animation-fill-mode: both;
}
```

but adding it after UIKit css overrides other animation classes that define these properties later on
