### ISSUE TITLE
Vendor prefixing for @supports

### ISSUE THREAD

**Issue by cheeaun** [parcel-bundler/lightningcss#341]
I noticed this bug on my side project where I heavily use `backdrop-filter` with `@supports`:

Example code:

```css
@supports (backdrop-filter: blur(10px)) {
  div {
    backdrop-filter: blur(10px);
  }
}
```

Running it with **PostCSS/Autoprefixer** will produce this *expected* result:

```css
@supports ((-webkit-backdrop-filter: blur(10px)) or (backdrop-filter: blur(10px))) {
  div {
    -webkit-backdrop-filter: blur(10px);
            backdrop-filter: blur(10px);
  }
}
```

But with **Parcel/lightningcss**, the result is this (**BUG**):

```css
@supports (backdrop-filter: blur(10px)) {
  div {
    -webkit-backdrop-filter: blur(10px);
            backdrop-filter: blur(10px);
  }
}
```

Safari [doesn't support un-prefixed `backdrop-filter`](https://caniuse.com/css-backdrop-filter), ignores the `@supports` part and never apply the `-webkit-backdrop-filter` styles 😭

Note: I'm currently using Parcel 2.8.0.
