### ISSUE TITLE
Ligthning generate :is with pseudo element

### ISSUE THREAD

**Issue by bakura10** [parcel-bundler/lightningcss#352]
Hi,

Considering the following code:

```
.foo {
  &::before {
    .bar & {
      color: blue;
    }
  }
}
```

ParcelCSS will generate the following CSS:

```
.bar :is(.foo:before){color:#00f}
```

[Playground URL](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20%26%3A%3Abefore%20%7B%5Cn%20%20%20%20.bar%20%26%20%7B%5Cn%20%20%20%20%20%20color%3A%20blue%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

However, using a pseudo element selector is not valid inside :is, so it should generate this instead:

```
.bar .foo:before{color:#00f}
```

**Comment by devongovett** [comment]
Actually I'm not convinced that this is valid for nesting either... https://drafts.csswg.org/css-nesting/#example-7145ff1e

**Comment by bakura10** [comment]
It seems you're right, this is a very odd limitation. Maybe Parcel should emit a warning here, I can imagine I won't be the first being caught by surprise here :D

**Comment by fuweichin** [comment]
For lightningcss 1.0.0-alpha.55, the double semicolon `::` of psuedo-element selector will always be transformed to single semicolon `:` (as psuedo-class selector) during bundle process regardless of browserslist. This doesn't make sense especially when the `--minify` option is not used.

**Comment by yisibl** [comment]
> It seems you're right, this is a very odd limitation. Maybe Parcel should emit a warning here, I can imagine I won't be the first being caught by surprise here :D

I filed a separate issue: https://github.com/parcel-bundler/lightningcss/issues/760

**Comment by yisibl** [comment]
For the following styles

## input

```css
dialog:modal, dialog:modal::backdrop {
  @starting-style {
    opacity: 0;
  }
  opacity: 1;
}
```

## output

```css
dialog:modal {
  opacity: 1;
}

@starting-style {
  dialog:modal {
    opacity: 0;
  }
}

dialog:modal::backdrop {
  opacity: 1;
}

@starting-style {
  dialog:modal::backdrop {
    opacity: 0;
  }
}
```

## expected

```css
dialog:modal, dialog:modal::backdrop {
  opacity: 1;
}
@starting-style {
  dialog:modal, dialog:modal::backdrop {
    opacity: 0;
  }
}
```
