### ISSUE TITLE
Marking a property with `!important` deletes the rule when nested

### ISSUE THREAD

**Issue by RobinMalfait** [parcel-bundler/lightningcss#356]
Hey! I think I found another bug, but this time while using the `!important` nested in an `@media`.

Currently I have this setup:

Input:
```css
.foo {
  @media (min-width: 640px) {
    color: red;
  }
}
```

Output:
```css
@media (min-width: 640px) {
  .foo {
    color: red;
  }
}
```

However, the moment I mark the color as `!important` the rule is removed.
```diff
 .foo {
   @media (min-width: 640px) {
-    color: red;
+    color: red !important;
   }
 }
```

That said, other properties underneath `.foo` will still work fine.
Input:
```css
.foo {
  color: blue !important;

  @media (min-width: 100px) {
    color: green;
  }

  @media (min-width: 640px) {
    color: red !important;
  }
}
```

Output:
```css
.foo {
  color: #00f !important;
}

@media (min-width: 100px) {
  .foo {
    color: green;
  }
}
```

Currently I'm using this workaround, but it feels like this might be a bug?

Workaround:
```css
.foo {
  @media (min-width: 640px) {
    & {
      color: red !important;
    }
  }
}
```
