### ISSUE TITLE
How are comments handled/exposed in the JS Visitor API.

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#366]
Comments are sometimes used in PostCSS plugin to :
- [disable/enable a feature](https://github.com/postcss/autoprefixer#control-comments)
- [conditionally remove CSS](https://www.npmjs.com/package/postcss-browser-comments)
- ...

I couldn't see an example with comments in the tests : https://github.com/parcel-bundler/lightningcss/blob/js-visitor/node/test/visitor.test.mjs

I don't think it is a major issue if comments are not exposed.
Personally I prefer not to use comments as a way to influence code.
More interesting to work within the CSS syntax.

```css
/**
 * 1. Add the correct box sizing in Firefox.
 */

hr {
  box-sizing: content-box; /* 1 */
}
```

vs.

```css
hr {
  box-sizing: todoOrDie(content-box, browserslist / Firefox);
}
```

_now I want to make a `todoOrDie` PostCSS plugin..._
