### ISSUE TITLE
Unnecessary vendor-prefixed or non-standard name pseudo-classes and values are not removed

### ISSUE THREAD

**Issue by chalkygames123** [parcel-bundler/lightningcss#369]
Lightning CSS should remove unnecessary vendor-prefixed or non-standard name pseudo-classes and values in the input CSS, but...

- Leaves them intact even when all target browsers support the unprefixed or standard name version
- Adds duplicate prefixed / standard name versions when one of the target browsers does not support the unprefixed or standard name version

Reproduction: https://github.com/chalkygames123/repro-lightningcss-unnecessary-vendor-prefixed-fallbacks

I explicitly specified pinned browser versions, which seem to be the latest version supported by Lightning CSS at the moment, to ensure reproducibility.

`input.css`, which contains non-standard name pseudo-classes, vendor-prefixed values, and vendor-prefixed properties:

```css
foo:-webkit-full-screen, foo:-moz-full-screen, foo:fullscreen {
  width: -webkit-fit-content;
  width: -moz-fit-content;
  width: fit-content;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
```

`npx lightningcss --targets 'chrome >= 100' input.css` produces:

```css
foo:-webkit-full-screen, foo:-moz-full-screen, foo:fullscreen { /* The first selector is unnecessary as Chrome >= 71 supports the standard name version. The second selector is unnecessary as Firefox is not included in the target browsers. */
  width: -webkit-fit-content; /* Unnecessary as Chrome >= 46 supports the unprefixed version. */
  width: -moz-fit-content; /* Unnecessary as Firefox is not included in the target browsers. */
  width: fit-content;
  -webkit-appearance: none; /* Unnecessary as Chrome >= 84 supports the unprefixed version. */
  -moz-appearance: none; /* Unnecessary as Firefox is not included in the target browsers. */
  appearance: none;
}
```

`npx lightningcss --targets 'firefox >= 98' input.css` produces:

```css
foo:-webkit-full-screen, foo:-moz-full-screen, foo:fullscreen { /* The first selector is unnecessary as Chrome is not included in the target browsers. The second selector is unnecessary as Firefox >= 64 supports the standard name version. */
  width: -webkit-fit-content; /* Unnecessary as Chrome is not included in the target browsers. */
  width: -moz-fit-content; /* Unnecessary as Firefox >= 94 supports the unprefixed version. */
  width: fit-content;
  -webkit-appearance: none; /* Unnecessary as Chrome is not included in the target browsers. */
  -moz-appearance: none; /* Unnecessary as Firefox >= 80 supports the unprefixed version. */
  appearance: none;
}
```

`npx lightningcss --targets 'chrome < 100' input.css` produces:

```css
foo:-webkit-full-screen, foo:-moz-full-screen, foo:fullscreen { /* The second selector is unnecessary as Firefox is not included in the target browsers. */
  width: -webkit-fit-content;
  width: -moz-fit-content; /* Unnecessary as Firefox is not included in the target browsers. */
  width: fit-content;
  -webkit-appearance: none;
  appearance: none;
}
```

`npx lightningcss --targets 'firefox < 98' input.css` produces:

```css
foo:-webkit-full-screen, foo:-moz-full-screen, foo:fullscreen { /* The first selector is unnecessary as Chrome is not included in the target browsers. */
  width: -webkit-fit-content; /* Unnecessary as Chrome is not included in the target browsers. */
  width: -moz-fit-content;
  width: fit-content;
  -moz-appearance: none;
  appearance: none;
}
```

Sorry in case I'm getting something wrong.
