### ISSUE TITLE
`@layer` names are unescaped in output

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#382]
[playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%40layer%20one.two%5C%5C20%20three%5C%5C%23four%5C%5C.five%20%7B%5Cn%20%20one.two%5C%5C20%20three%5C%5C%23four%5C%5C.five%20%7B%5Cn%20%20%20%20background%3A%20%5C%5C75%20Rl(test.png)%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%2C%5Cn%20%20Url(url)%20%7B%5Cn%20%20%20%20url.url%20%3D%20'http%3A%2F%2Fexample.com%2F'%20%2B%20url.url%3B%5Cn%20%20%20%20return%20url%3B%5Cn%20%20%7D%2C%5Cn%20%20Declaration%3A%20%7B%5Cn%20%20%20%20custom%3A%20%7B%5Cn%20%20%20%20%20%20size(property)%20%7B%5Cn%20%20%20%20%20%20%20%20if%20(property.value%5B0%5D.type%20%3D%3D%3D%20'length')%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20let%20value%20%3D%20%7B%20type%3A%20'length-percentage'%2C%20value%3A%20%7B%20type%3A%20'dimension'%2C%20value%3A%20property.value%5B0%5D.value%20%7D%20%7D%3B%5Cn%20%20%20%20%20%20%20%20%20%20return%20%5B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7B%20property%3A%20'width'%2C%20value%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7B%20property%3A%20'height'%2C%20value%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%5D%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

```css
@layer one.two\20 three\#four\.five {
  one.two\20 three\#four\.five {
    background: \75 Rl(test.png);
  }
}
```

becomes :

```css
@layer one.two three#four.five {
  one.two\ three\#four\.five {
    background: url("http://example.com/test.png");
  }
}
```

The selector escaping is handled correctly but the `@layer` name is not.
