### ISSUE TITLE
Custom at-rule style parsing

### ISSUE THREAD

**Issue by danteissaias** [parcel-bundler/lightningcss#391]
I am trying to create the following transform:

```css
/* Input */
@breakpoints {
   .mt-1 { margin-top: 1px };
}

/* Output */
@media all {
  .mt-1 { margin-top: 1px };
}

@media (max-width: 600px) {
  .sm\:mt-1 { margin-top: 1px };
}

@media (max-width: 800px) {
  .md\:mt-1 { margin-top: 1px };
}
```

How can I parse unknown at-rules' `block` property as a style declaration?
