### ISSUE TITLE
Already prefixed backdrop-filter results in two prefixed declarations

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/lightningcss#403]
```css
body {
  -webkit-backdrop-filter: blur(20px);
  backdrop-filter: blur(20px);
}
```
results in
```css
body {
  -webkit-backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  backdrop-filter: blur(20px);
}
```

Just like https://github.com/parcel-bundler/lightningcss/issues/237

[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6553600%2C%22safari%22%3A917504%7D%2C%22source%22%3A%22body%20%7B%5Cn%20%20-webkit-backdrop-filter%3A%20blur(20px)%3B%5Cn%20%20backdrop-filter%3A%20blur(20px)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22%22%7D)

**Comment by LeoniePhiline** [comment]
In the above playground link, the result is now:

```css
body {
  backdrop-filter: blur(20px);
}
```

That's a regression, since Safari needs `-webkit-backdrop-filter`.

**Comment by LeoniePhiline** [comment]
# Repro:

lightningcss 1.21.1 and lightningcss-cli 1.21.5 mis-transform the following:

## Source

This source was generated by parcel with the `--no-optimize` flag.

```css
@supports (
  (-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))
) {
  :root {
    --some-color: #000000e6;
  }
}

.cc-bottom {
  -webkit-backdrop-filter: saturate(250%) blur(8px);
  backdrop-filter: saturate(250%) blur(8px);
}

.transition {
  transition-property:
    color,
    background-color,
    border-color,
    text-decoration-color,
    fill,
    stroke,
    opacity,
    box-shadow,
    transform,
    filter,
    -webkit-backdrop-filter,
    backdrop-filter;
}

@supports (
  (-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))
) {
  .supports-bg-filter\:bg-blur-saturate {
    -webkit-backdrop-filter: saturate(250%) blur(8px);
    backdrop-filter: saturate(250%) blur(8px);
  }
}
```

Into this result:

## Result

This output was generated by lightningcss-cli by invoking `pnpm exec lightningcss --targets 'defaults' input.css -o output.css`

```css
@supports ((-webkit-backdrop-filter: blur(8px))) or ((-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))) {
  :root {
    --some-color: rgba(0, 0, 0, .9);
  }
}

.cc-bottom {
  backdrop-filter: saturate(250%) blur(8px);
}

.transition {
  transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, -webkit-backdrop-filter, -webkit-backdrop-filter, backdrop-filter;
}

@supports ((-webkit-backdrop-filter: blur(8px))) or ((-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))) {
  .supports-bg-filter\:bg-blur-saturate {
    backdrop-filter: saturate(250%) blur(8px);
  }
}
```

## Notes:

- `@supports`: `(-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))` has the webkit prefixed part duplicated.
- All `-webkit-backdrop-filter:` rules are removed.

**Comment by LeoniePhiline** [comment]
# Regression in lightningcss 1.18.0

All results produced with `pnpm exec lightningcss --targets 'defaults' input.css -o output.css` after `pnpm i -D lightningcss@1.17.1` / `pnpm i -D lightningcss@1.18.0`.

The following works with lightningcss 1.17.1 and broke with lightningcss 1.18.0:

## Source

```css
@supports (
  (-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))
) {
  :root {
    --some-color: #000000e6;
  }
}
```

## Good result in lightningcss 1.17.1

```css
@supports ((-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))) {
  :root {
    --some-color: rgba(0, 0, 0, .9);
  }
}
```

## Bad result in lightningcss 1.18.0+

```css
@supports ((-webkit-backdrop-filter: blur(8px))) or ((-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))) {
  :root {
    --some-color: rgba(0, 0, 0, .9);
  }
}
```

**Comment by LeoniePhiline** [comment]
# Duplicated `-webkit-backdrop-filter` in `transition-property`: Broken in all versions since at least lightningcss 1.14.0

All results produced with `pnpm exec lightningcss --targets 'defaults' input.css -o output.css` after `pnpm i -D lightningcss@1.14.0`, `@1.15.0`, `@1.16.0`, `@1.75.0`, `@1.18.0`, `@1.19.0`, `@1.20.0`, `@1.21.0`, `@1.21.1`, `@1.21.2`, `@1.21.3`, `@1.21.4`, `@1.21.5`.

The following does not work in any version since at least lightningcss 1.14.0 ([older versions were apparently yanked](https://www.npmjs.com/package/lightningcss?activeTab=versions)):

## Source

```css
.transition {
  transition-property: -webkit-backdrop-filter, backdrop-filter;
}
```

## Bad result in all available lightningcss versions

```css
.transition {
  transition-property: -webkit-backdrop-filter, -webkit-backdrop-filter, backdrop-filter;
}
```
