### ISSUE TITLE
Use text-decoration-line rather than shorthand for Safari

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/lightningcss#411]
[Example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A851968%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20%26%3Afocus-ring%20%7B%5Cn%20%20%20%20text-decoration%3A%20underline%3B%5Cn%20%20%20%20text-decoration-style%3A%20double%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

This currently doesn't work in Safari - we need to use the individual properties instead. This is similar to #146 but for a different property. Need to get browser support data from MDN.

**Comment by djmtype** [comment]
Why is this closed? This doesn't appear to be fixed. Tested on Safari 18.4. Using "defaults" browserslist, too.


Input: 

```css
.example {
text-decoration: underline;
text-decoration-style: solid;
text-decoration-color: currentColor;
text-decoration-thickness: 0.2em;
text-underline-offset: 0.4em;
}
```

Output: 

```css
.example {
text-underline-offset: 0.4em;
text-decoration: underline 0.2em;
}
```
