### ISSUE TITLE
Merge non-adjacent @layer rules

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/lightningcss#414]
Input:

```css
@layer one {
  body {
    background: red;
  }
}

@layer two {
  body {
    background: green;
  }
}

@layer one {
  body {
    background: yellow;
  }
}
```

Output should be:

```css
@layer one {
  body {
    background: yellow;
  }
}

@layer two {
  body {
    background: green;
  }
}
```

This is safe because layers apply in the order they are _first_ defined, unlike other rules.
