### ISSUE TITLE
font-style stripped from @font-face

### ISSUE THREAD

**Issue by Woedenaz** [parcel-bundler/lightningcss#416]
It seems by default:

```css
@font-face {
  font-family: Inter;
  font-style: oblique 0deg 10deg;
  font-weight: 100 900;
  src: url("../fonts/Inter.var.woff2?v=3.19") format("woff2");
  font-display: swap;
}
```
becomes:
```css
@font-face {
  font-family: Inter;
  font-weight: 100 900;
  src: url("../fonts/Inter.var.woff2?v=3.19") format("woff2");
  font-display: swap;
}
```

I've tried using visitors to fix it but I seem unable to work it out. 
Without the `font-style: oblique 0deg 15deg;` variable fonts do not function correctly.

Would definitely appreciate a solution to this!
