### ISSUE TITLE
Support for top-level Nesting selector `&`

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#422]
Now this is a legal CSS rule:

```css
& {
  color: blue;
}

& .foo {
    color: green;
}
```

Spec: https://drafts.csswg.org/css-nesting-1/#nest-selector
See also: https://chromium-review.googlesource.com/c/chromium/src/+/4206786
