### ISSUE TITLE
Further optimize `@layer` minification opportunities

### ISSUE THREAD

**Issue by adamwathan** [parcel-bundler/lightningcss#423]
Cascade layers support a few things that Lightning CSS doesn't currently take into consideration:

- Nested layers both by nesting directly as well as using dot notation to insert into a nested layer
- Anonymous layers, which are treated as unique and can't be combined
- Predefined layer order using `@layer` without a block

That means input like this:

```css
@layer one, two, three;

@layer three.utilities {
  .bg-black {
    background: #000;
  }
}

@layer two {
  body {
    background: red;
  }
  @layer base {
    body {
      font-size: 10px;
    }
  }
}

@layer {
  .class-1 {
    color: blue;
  }
}

@layer three {
  @layer utilities {
    .mt-10 {
      margin-top: 10px;
    }
  }
  html {
    color: white;
  }
}

@layer two.base {
  h1 {
    font-size: 24px;
  }
}

@layer two {
  h2 {
    font-size: 20px;
  }
}

@layer one {
  p {
    font-size: 16px;
  }
}

@layer {
  .class-2 {
    color: red;
  }
}
```

...can be minified to this sort of shape:

```css
@layer one {
  p {
    font-size: 16px;
  }
}

@layer two {
  body {
    background: red;
  }
  h2 {
    font-size: 20px;
  }
  @layer base {
    body {
      font-size: 10px;
    }
    h1 {
      font-size: 24px;
    }
  }
}

@layer three {
  @layer utilities {
    .bg-black {
      background: #000;
    }
    .mt-10 {
      margin-top: 10px;
    }
  }
  html {
    color: white;
  }
}

@layer {
  .class-1 {
    color: blue;
  }
}

@layer {
  .class-2 {
    color: red;
  }
}
```

This is unfortunately complicated, hah 😄 It would be pretty amazing to be able to handle this sort of thing at the minification layer as I have to imagine it makes the browser's job easier.

I ask selfishly because I'm anticipating a future for Tailwind CSS where we leverage cascade layers to avoid a bunch of the complex sorting logic that exists in the framework right now, and instead generate code that looks like this:

```css
@layer defaults, base, components, utilities, variants;

@layer base {
  html { /* ... */ }
  /* ... */
}

@layer components {
  .container { /* ... */ }
}

.shadow-sm {
  @layer defaults {
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000
  }
  @layer utilities {
    --tw-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);
    --tw-shadow-colored: 0 1px 2px 0 var(--tw-shadow-color);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)
  }
}

.blur {
  @layer defaults {
    --tw-blur:  ;
    --tw-brightness:  ;
    --tw-contrast:  ;
    --tw-grayscale:  ;
    --tw-hue-rotate:  ;
    --tw-invert:  ;
    --tw-saturate:  ;
    --tw-sepia:  ;
    --tw-drop-shadow:  
  }
  @layer utilities {
    --tw-blur: blur(8px);
    filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow)
  }
}

.hover\:scale-125 {
  @layer defaults {
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1
  }
  @layer variants {
    &:hover {
      --tw-scale-x: 1.25;
      --tw-scale-y: 1.25;
      transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
    }
  }
}
```

...and delegate all of the work for processing nesting and minification to Lightning CSS (or our own separate production-ifying layer if needed, not trying to make demands here of course!) to get output more like this:

```css
@layer defaults {
  .shadow-sm {
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000;
  }
  .blur {
    --tw-blur: ;
    --tw-brightness: ;
    --tw-contrast: ;
    --tw-grayscale: ;
    --tw-hue-rotate: ;
    --tw-invert: ;
    --tw-saturate: ;
    --tw-sepia: ;
    --tw-drop-shadow: ;
  }
  .hover\:scale-125 {
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
  }
}

@layer base {
  html { /* ... */ }
  /* ... */
}

@layer components {
  .container { /* ... */ }
}

@layer utilities {
  .shadow-sm {
    --tw-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);
    --tw-shadow-colored: 0 1px 2px 0 var(--tw-shadow-color);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000),
      var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
  }
  .blur {
    --tw-blur: blur(8px);
    filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast)
      var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert)
      var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
  }
}

@layer variants {
  .hover\:scale-125:hover {
    --tw-scale-x: 1.25;
    --tw-scale-y: 1.25;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y))
      rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y))
      scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  }
}
```

Thought it was worth raising just to bring some awareness at least to all of these extra cascade layer features that might need to be considered.

This is a really fantastic post that covers all of this stuff in quite a bit of depth:

https://css-tricks.com/css-cascade-layers/

**Comment by devongovett** [comment]
Yeah what I implemented in #414 only covers layers defined in the same css rule list, not nested ones. We could potentially flatten some of these. However there are some cases where it isn't possible like layer blocks inside media rules or nested in style rules where it wouldn't be safe.

**Comment by jjenzz** [comment]
@devongovett i'm not sure whether to create a separate issue for this or not (lmk) but it would also be super handy if it could optimise using `browserslist` to manually group styles for browsers w/o `@layer` support.

i've set Chrome version [real low here](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A655360%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40layer%20utilties%2C%20reponsive%3B%5Cn%5Cn%40layer%20utilties%20%7B%5Cn%20%20.p-1%20%7B%5Cn%20%20%20%20padding%3A%2010px%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40layer%20responsive%20%7B%5Cn%20%20%40media%20(min-width%3A%20300px)%20%7B%5Cn%20%20%20%20.md_p-1%20%7B%5Cn%20%20%20%20%20%20padding%3A%2010px%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40layer%20utilties%20%7B%5Cn%20%20.p-2%20%7B%5Cn%20%20%20%20padding%3A%2020px%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40layer%20responsive%20%7B%5Cn%20%20%40media%20(min-width%3A%20300px)%20%7B%5Cn%20%20%20%20.md_p-2%20%7B%5Cn%20%20%20%20%20%20padding%3A%2020px%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) and you can see the `@layer` rules still exist. I expected it to do the same grouping but unwrap them. 

Perhaps i am misunderstanding how browserslist is intended to be used here tho?

**Comment by devongovett** [comment]
it's not safe for us to compile layers away completely because there might be other css on the page that uses them, or has its own layers (and unlayered rules have higher precedence). perhaps there could be an opt-in way of doing it, but that would go along with other unsafe optimizations that have been discussed in the past.

**Comment by jjenzz** [comment]
that makes sense, and an opt-in wld be fab. i haven't followed the discussions around unsafe optimisations tho, what's the context there?

**Comment by devongovett** [comment]
aedf6b675705ad385b78bd35b72858b9b68875e8 implements more `@layer` optimizations, mainly inlining layer blocks into pre-declared layer statements. So something like this:

```css
@layer foo, bar, baz;

@layer bar {
  .bar { color: red }
}

@layer baz {
  .baz { color: red }
}

@layer foo {
  .foo { color: red }
}
```

minifies to:

```css
@layer foo {
  .foo { color: red }
}

@layer bar {
  .bar { color: red }
}

@layer baz {
  .baz { color: red }
}
```

the pre-declarations are removed and the layer blocks are placed in the correct order.

Still doesn't do anything with nested layers though. The merging only happens on a single level at a time. But if you set up your rules to be generated this way, it should be optimal.
