### ISSUE TITLE
Support `@media` nesting

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#424]
Spec: https://drafts.csswg.org/css-nesting-1/#conditionals

```css
.foo {
  display: grid;

  @media (orientation: landscape) {
    grid-auto-flow: column;

    @media (min-width > 1024px) {
      max-inline-size: 1024px;
    }
  }
}

/* equivalent to */
  .foo { display: grid; }

  @media (orientation: landscape) {
    .foo {
      grid-auto-flow: column;
    }
  }

  @media (orientation: landscape) and (min-width > 1024px) {
    .foo {
      max-inline-size: 1024px;
    }
  }
```

![image](https://user-images.githubusercontent.com/2784308/218293535-0f58cdb4-48ee-4780-b613-ac900ef614f4.png)
