### ISSUE TITLE
Duplicate 'image-set' generated with certain browserslist targets

### ISSUE THREAD

**Issue by jahudka** [parcel-bundler/lightningcss#436]
Minimal repro:

```css
/* styles.css */
body {
  background-image: image-set(
    url('./bg.jpg') 1x,
    url('./bg@2x.jpg') 2x
  );
}
```

```javascript
// test.mjs
import browserslist from 'browserslist';
import { transform, browserslistToTargets } from 'lightningcss';
import { readFile } from 'fs/promises';
import { resolve } from 'path';

const code = await readFile(resolve('styles.css'));
const result = transform({
  filename: 'styles.css',
  code,
  minify: false,
  sourceMap: false,
  targets: browserslistToTargets(browserslist('>=0.0%')),
});

console.log(result.code.toString());
```

The resulting code generated by running `node test.mjs` looks like this:

```css
body {
  background-image: image-set("./bg.jpg" 1x, "./bg@2x.jpg" 2x);
  background-image: -webkit-image-set(url("./bg.jpg") 1x, url("./bg@2x.jpg") 2x);
  background-image: image-set("./bg.jpg" 1x, "./bg@2x.jpg" 2x);
}
```

The third `background-image` is a duplicate of the first one. As soon as I raise the Browserslist target to something even the tiniest bit saner than `>=0.0%`, e.g. `>=0.01%`, the problem disappears. I don't think this is a very serious issue since probably very few people use a Browserslist target of `>=0.0%`, but as I'm unsure what the cause is and it might be potentially interesting for you guys (in case it points to an actual bug with potentially more harmful effects), I thought I'd report it. This happens on LightningCSS version 1.19.0, NodeJS v18.14.0, MacOS 11.3.
