### ISSUE TITLE
lab, lch, oklab and oklch syntax lowering does not support numeric values for L component

### ISSUE THREAD

**Issue by fpapado** [parcel-bundler/lightningcss#445]
The `lab()`, `lch()`, `oklab()` and `oklch()` functional notations support a numeric value for the L component. However, lightningcss only supports percentage values for those components, and bails out if a number is used.

In other words, these two declarations should be equivalent and lowered to `background: #777`:
 
```css
.lch-percentage {
  background: lch(50% 0 223.97);
}
/* This is a valid representation as well (L [0,100] for lch()) */
.lch-number {
  background: lch(50 0 223.97);
}
```

But this is the output instead:
```css
.lch-percentage {
  background: #777;
  background: lch(50% 0 223.97);
}

/* Stays intact, instead of being lowered */
.lch-number {
  background: lch(50 0 223.97);
}
```

[Link to the playground, showing the lack of lowering for the numeric L component](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.lch-percentage%20%7B%5Cn%20%20background%3A%20lch(50%25%200%20223.97)%3B%5Cn%7D%5Cn%2F*%20This%20is%20a%20valid%20representation%20as%20well%20(L%200-100)%20*%2F%5Cn.lch-number%20%7B%5Cn%20%20background%3A%20lch(50%200%20223.97)%3B%5Cn%7D%5Cn%5Cn.lab-percentage%20%7B%5Cn%20%20background%3A%20lab(50%25%200%200)%3B%5Cn%7D%5Cn%2F*%20This%20is%20a%20valid%20representation%20as%20well%20(L%200-100)%20*%2F%5Cn.lab-number%20%7B%5Cn%20%20background%3A%20lab(50%200%200)%3B%5Cn%7D%5Cn%5Cn.oklch-percentage%20%7B%5Cn%20%20background%3A%20oklch(56.9%25%200%20102.07)%3B%5Cn%7D%5Cn%2F*%20This%20is%20a%20valid%20representation%20as%20well%20*%2F%5Cn%2F*%20In%20oklch%2C%20L%20is%20a%200-1%20number%20*%2F%5Cn.oklch-number%20%7B%5Cn%20%20background%3A%20oklch(0.569%200%20102.07)%3B%5Cn%7D%5Cn%5Cn.oklab-percentage%20%7B%5Cn%20%20background%3A%20oklab(56.9%25%200%200)%3B%5Cn%7D%5Cn%2F*%20This%20is%20a%20valid%20representation%20as%20well%20*%2F%5Cn%2F*%20In%20oklab%2C%20L%20is%20a%200-1%20number%20*%2F%5Cn.oklab-number%20%7B%5Cn%20%20background%3A%20oklab(0.569%200%200)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

## Expected behaviour

- `lch()` should allow numeric values of [0,100] for the L component
- `lab()` should allow numeric values of [0,100] for the L component
- `okch()` should allow numeric values of [0,1] for the L component
- `oklab()` should allow numeric values of [0,1] for the L component

Note the difference in the numeric range: `lch()` and `lab()` define them as [0,100] corresponding to 0% and 100%, while `oklch` and `oklab` define them as [0,1.0] corresponding to 0% and 100%.

[Reference for `lch()` and `lab()` numeric range](https://www.w3.org/TR/css-color-4/#specifying-lab-lch)
[Reference for `oklch()` and `oklab()` numeric range](https://www.w3.org/TR/css-color-4/#specifying-oklab-oklch)

Please let me know if there is any other information that I can provide, or whether I missed something! I would be happy to contribute a PR for this :)
