### ISSUE TITLE
Missing CSS module renaming for nested @keyframes

### ISSUE THREAD

**Issue by joelmoss** [parcel-bundler/lightningcss#450]
I have the following CSS which has a nested `@keyframes`:

```css
.loading {
  animation: ball;

  @keyframes ball {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }
}
```

Passing this to lightningcss with nesting and css modules enabled gives me this out ouput:

```css
.EgL3uq_loading {
  animation: EgL3uq_ball;
  @keyframes ball {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }
}
```

Which as you can see, renames the `ball` keyframe when it is used, but does not rename the actual declaration.

Un-nesting the `@keyframe` results in correctly renaming both the call and the declaration.

thx
