### ISSUE TITLE
`@media` range notation can result in float values in feature that only accept integers

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#454]
https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%40media%20(color%20%3E%202)%20%7B%5Cn.foo%20%7Bcolor%3A%20red%3B%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

```css
@media (color > 2) {
.foo {color: red;}
}
```

becomes :

```css
@media (min-color: 2.001) {
  .foo {
    color: red;
  }
}
```

`color` however doesn't accept `<number>`
