### ISSUE TITLE
Discussion: Allow to use global css grid names (not hashed like in post-cssmodules)

### ISSUE THREAD

**Issue by mhsdesign** [parcel-bundler/lightningcss#460]
It seems this topic has been briefly discussed in: https://github.com/parcel-bundler/lightningcss/issues/144
And i was wondering if there are plans or if it fits your philosophy to have an option to allow css grid names to be used without hashing (scoped to the current module).

If youre wondering what our usecase is:
Previously we have used post-cssmodules, where the grid-areas are global, and thus they could be consumed by plugin authors to extend/modify our app in unplanned ways. (I agree its not pretty, but it works - so why not ^^)

To me it seems that there are currently two workarounds to achieve this: 

A:
by using css variables
```css
.container {
    --grid-areas: "left top right" "left main right";
    --grid-area-right: right;
    grid-template-areas: var(--grid-areas);
}

.gridRight {
    grid-area: var(--grid-area-right);
}
```

B:
by using some global css file and compose from global:
`global.css`
```css
.my-css-grid {
    grid-template-areas: "left top right" "left main right";
}

.my-css-grid-right {
  grid-area: right;
}
```

`my.module.css`
```css
.container {
    composes: my-css-grid from global;
}
.gridRight {
    composes: my-css-grid-right from global;
}
```

What do you say? Does it make sense as native feature?
