### ISSUE TITLE
`@media` range notations seem to produce different results based on the character length of the values

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#462]
```css
@media (width < 1000px) {
  .a {
    color: green;
  }
}

@media (width < 1001px) {
  .a {
    color: green;
  }
}
```

becomes :

```css
@media (max-width: 999.999px) {
  .a {
    color: green;
  }
}

@media (max-width: 1001px) {
  .a {
    color: green;
  }
}

```
https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A5242880%7D%2C%22source%22%3A%22%40media%20(width%20%3C%201000px)%20%7B%5Cn%20%20.a%20%7B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(width%20%3C%201001px)%20%7B%5Cn%20%20.a%20%7B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

Is this intentional?
