### ISSUE TITLE
Nesting misses selector minification opportunity

### ISSUE THREAD

**Issue by rik** [parcel-bundler/lightningcss#464]
# With CSS nesting
```css
a {
    cursor:pointer;
    + b {
        cursor:pointer;
    }
}
```
compiles to 
```css
a{cursor:pointer}a+b{cursor:pointer}
```

# Without CSS nesting
```css
a {
    cursor:pointer;
}
a + b {
    cursor:pointer;
}
```
compiles to
```css
a,a+b{cursor:pointer}
```

**Comment by phoenix-ru** [comment]
I discovered a more "severe" case with it. Consider the following input:
```css
.test {
    background: yellow;
}

.test {
    background: yellow;
}

.test, .test {
    background: yellow;
}

.test + .test {
    background: yellow;
}
```

From a human perspective, it's clear that there is an enormous amount of duplication, and all that should be reduced to a single rule like that:
```css
.test,.test+.test{background:#ff0}
```
In fact, that is [exactly what CSSNANO does](https://cssnano.co/playground/#eyJpbnB1dCI6Ii50ZXN0IHtcbiAgICBiYWNrZ3JvdW5kOiB5ZWxsb3c7XG59XG5cbi50ZXN0IHtcbiAgICBiYWNrZ3JvdW5kOiB5ZWxsb3c7XG59XG5cbi50ZXN0LCAudGVzdCB7XG4gICAgYmFja2dyb3VuZDogeWVsbG93O1xufVxuXG4udGVzdCArIC50ZXN0IHtcbiAgICBiYWNrZ3JvdW5kOiB5ZWxsb3c7XG59IiwiY29uZmlnIjoiY3NzbmFuby1wcmVzZXQtYWR2YW5jZWQifQ==).

However, `lightningcss` does not take the opportunity and instead produces an obviously duplicated code:
```css
.test,.test,.test,.test+.test{background:#ff0}
```

Now, one might think that it is a bit too much for the optimizer. Try that with `nesting: true`.
```css
.test {
    background: yellow;

    & {
        background: yellow
    }

    &, & {
        background: yellow
    }

    & + & {
        background: yellow
    }
}
```

Which produces even more code, surprisingly
```css
.test{background:#ff0}.test,.test,.test,.test+.test{background:#ff0}
```

FYI, code to minify is the following:
```rs
stylesheet
        .minify(MinifyOptions {
            targets: Some(Browsers {
                chrome: Some(100 << 16),
                ..Default::default()
            }),
            ..Default::default()
        })
        .unwrap();
```
