### ISSUE TITLE
Dedupe custom properties (CSS variables) in :root

### ISSUE THREAD

**Issue by wingleung** [parcel-bundler/lightningcss#466]
First of all, nice work with the performance of this tool 💯 

I noticed there is no deduplication when we have duplicate custom properties defined in :root pseudo classes.
Can we dedupe those custom properties like we dedupe the css properties?

### Input

```css
:root {
    --some-css-variable: red;
}

:root {
    --some-css-variable: blue;
}
``` 

### Expected output

```css
:root {
    --some-css-variable: blue;
}
```

### Actual output

```css
:root {
    --some-css-variable: red;
}

:root {
    --some-css-variable: blue;
}
```
