### ISSUE TITLE
Instability of output during repeated formatting when parent element needs vendor prefixes

### ISSUE THREAD

**Issue by thecrypticace** [parcel-bundler/lightningcss#478]
Hi! 👋 

While working in the Tailwind CSS tests a change in Lightning CSS 1.19+ caused instability in the input/output when formatting multiple times. What I've done here is taken the input and formatted it, taken that output and formatted it again, and done the same thing again.

Basically this:

- `format(input)`
- `format(format(input))`
- `format(format(format(input)))`

The reason we do this is that we format both the received input as well as the expected output files with Lightning CSS — this us perform a meaningful diff even when the input might actually produce rules that are not merged due to slight formatting differences. If we try to update the expected file with the output Lightning CSS gives us it's still not 100% correct because when it formats it again it'll change.

For example, this CSS is produces different output when passed back into lightning CSS multiple times:

```css
/* Original Input */
.foo:placeholder-shown .bar { color: red; }
.foo:autofill .baz { color: red; }

/* Processed 1 time with Lightning CSS */
.foo:placeholder-shown .bar,.foo:autofill .baz{color:red}

/* Processed 2 times with Lightning CSS */
.foo:-webkit-placeholder-shown .bar,.foo:-webkit-autofill .baz{color:red}.foo:placeholder-shown .bar,.foo:autofill .baz{color:red}

/* Processed 3 times with Lightning CSS */
.foo:-webkit-placeholder-shown .bar,.foo:-webkit-autofill .baz,.foo:-webkit-placeholder-shown .bar,.foo:-webkit-autofill .baz{color:red}
```

However, this CSS produces the same output when passed back into lightning CSS multiple times — the difference here is that the thing with the vendor-prefixable pseudo-class is not the last item in the selector:

```css
/* Original Input */
.bar:placeholder-shown { color: red; }
.baz:autofill { color: red; }

/* Processed 1 time with Lightning CSS */
.bar:placeholder-shown{color:red}.baz:-webkit-autofill{color:red}.baz:autofill{color:red}

/* Processed 2 times with Lightning CSS */
.bar:placeholder-shown{color:red}.baz:-webkit-autofill{color:red}.baz:autofill{color:red}

/* Processed 3 times with Lightning CSS */
.bar:placeholder-shown{color:red}.baz:-webkit-autofill{color:red}.baz:autofill{color:red}
```

So it appears that when a parent element needs vendor prefixes on a selector the prefixes are not added immediately but only in subsequent formatting passes. However, if the last item in a selector is the one needing a vendor prefix it seems to be added as expected.

This is reproducible in the Lightning CSS playground as well:
- [Pass 1](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6750208%7D%2C%22source%22%3A%22.foo%3Aplaceholder-shown%20.bar%20%7B%20color%3A%20red%3B%20%7D%5Cn.foo%3Aautofill%20.baz%20%7B%20color%3A%20red%3B%20%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
- [Pass 2](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6750208%7D%2C%22source%22%3A%22.foo%3Aplaceholder-shown%20.bar%2C.foo%3Aautofill%20.baz%7Bcolor%3Ared%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
- [Pass 3](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6750208%7D%2C%22source%22%3A%22.foo%3A-webkit-placeholder-shown%20.bar%2C.foo%3A-webkit-autofill%20.baz%7Bcolor%3Ared%7D.foo%3Aplaceholder-shown%20.bar%2C.foo%3Aautofill%20.baz%7Bcolor%3Ared%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
- [Pass 4](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6750208%7D%2C%22source%22%3A%22.foo%3A-webkit-placeholder-shown%20.bar%2C.foo%3A-webkit-autofill%20.baz%2C.foo%3A-webkit-placeholder-shown%20.bar%2C.foo%3A-webkit-autofill%20.baz%7Bcolor%3Ared%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
