### ISSUE TITLE
Output CSS lose background-size

### ISSUE THREAD

**Issue by DixCouleur** [parcel-bundler/lightningcss#486]
Input
```css
.bg {
  background: url("abc.jpg");
  background-size: contain;
}

.webp .bg {
  background: url("abc.webp");
}
```

Output
```css
.bg {
  background: url("abc.jpg") 0 0 / contain;
}

.webp .bg {
  background: url("abc.webp");
}
```

The output css does not specify `background-size` property

[Playground link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.bg%20%7B%5Cn%20%20background%3A%20url(%5C%22abc.jpg%5C%22)%3B%5Cn%20%20background-size%3A%20contain%3B%5Cn%7D%5Cn%5Cn%5Cn.webp%20.bg%20%7B%5Cn%20%20background%3A%20url(%5C%22abc.webp%5C%22)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
