### ISSUE TITLE
Mixins override order of rules in declarations; unexpected cascade behavior

### ISSUE THREAD

**Issue by patrulea** [parcel-bundler/lightningcss#497]
I’m using the [snippet found in the docs](https://lightningcss.dev/transforms.html#custom-at-rules) to apply mixins as at-rules. But its behavior is unlike SASS and PostCSS Mixins as it renders the rules inside a second declaration below where it’s supposed to be.

How can I fix this?  
(I’m not good with JavaScript)

**Input**

```css
@mixin layout__fullscreen {
  position: fixed;
  inset: 0;
}
.nav {
  @apply layout__fullscreen;
  bottom: unset;
}
```

**Current Output**

```css
.nav {
  bottom: unset;
}
.nav {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
```

**Expected Output**

```css
.nav {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  bottom: unset;
}
```

---

**Current Lightning CSS configuration**

```js
let mixins = new Map();
let { code } = transform({
  minify: false,
  sourceMap: false,
  targets: browserslistToTargets(browserslist("> 0.2% and not dead")),
  drafts: {
    nesting: true,
    customMedia: true
  },
  customAtRules: {
    mixin: {
      prelude: "<custom-ident>",
      body: "style-block"
    },
    apply: {
      prelude: "<custom-ident>"
    }
  },
  visitor: {
    Rule: {
      custom: {
        mixin(rule) {
          mixins.set(rule.prelude.value, rule.body.value);
          return [];
        },
        apply(rule) {
          return mixins.get(rule.prelude.value);
        }
      }
    }
  },
  code: Buffer.from(content)
});
```
