### ISSUE TITLE
Later transform rules do not override previous transform rules

### ISSUE THREAD

**Issue by damijank** [parcel-bundler/lightningcss#499]
I have found a problem which seems to be specific to `transform` rules. **Later rules do not override previous ones.**

I tested this with the latest version **`1.20.0`**.

We are using _mixins_ (before processing, outside of lightningCss) and that's why same rules can be repeated in the same declaration. For example, a theme imports defaults and overrides some of the rules.

For all rules I've inspected, the resulting minified CSS always has the **latest** rule, as it should be... except for `transform`, for which it always seems to have the **first** rule.

**Input:**

```CSS
.first-test-class {
        position: absolute;
        transform: translateX(-50%);
        -webkit-transform: translateX(-50%);
        -moz-transform: translateX(-50%);
        -ms-transform: translateX(-50%);
        position: relative;
        transform: none;
}
.second-test-class {
        left: 20px;
        transform: translateY(-50%);
        left: 0;
        transform: translateY(-30%);
        left: -10px;
        transform: none;
}
.third-test-class {
        left: 20px;
        transform: translateY(-50%);
        left: 0;
        transform: translateY(-30%);
}
.fourth-test-class {
        color: red;
        transform: translate3d(-50%, 50%, 0);
        color: blue;
        transform: none;
}
.fifth-test-class {
        color: red;
        transform: none;
        color: blue;
        transform: translateX(-50%);
}
```

**Output** (formatted)**:**
```CSS
.first-test-class {
    position: relative;
    -webkit-transform: translate(-50%);
    transform: translate(-50%)
}
.second-test-class {
    left: -10px;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%)
}
.third-test-class {
    left: 0;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%)
}
.fourth-test-class {
    color: red;
    color: #00f;
    -webkit-transform: translate(-50%,50%);
    transform: translate(-50%,50%)
}
.fifth-test-class {
    color: red;
    color: #00f;
    -webkit-transform: none;
    transform: none
}
```

**Expected output** (formatted)**:**
```CSS
.first-test-class {
    position: relative;
    -webkit-transform: none;
    transform: none
}
.second-test-class {
    left: -10px;
    -webkit-transform: none;
    transform: none
}
.third-test-class {
    left: 0;
    -webkit-transform: translateY(-30%);
    transform: translateY(-30%)
}
.fourth-test-class {
    color: #00f;
    -webkit-transform: none;
    transform: none
}
.fifth-test-class {
    color: #00f;
    -webkit-transform: translate(-50%);
    transform: translate(-50%)
}
```

As a side note, for `color` all rules seem to be included. This gives correct results in the browser, but it's not optimal... only the latest rule should be in the final CSS.

A second side note, `translate3d` is faster in most browsers. I know minifying is all about producing the smallest payload possible, but for performance reasons, maybe it could be considered that transforms are not "minified away" but rather optimized with performance in mind. Maybe for all `translate` rules, but especially when the original CSS has used `translate3d` in the first place.
