### ISSUE TITLE
Splitting to multiple files

### ISSUE THREAD

**Issue by jacobrask** [parcel-bundler/lightningcss#500]
In our design system we generate a separate file for desktop styles that we load using `<link media>`. Currently we maintain a separate entry point for these styles that we transform separately, but I'd prefer to be able to split the stylesheet depending on media queries, something like [postcss-extract-media-query](https://github.com/SassNinja/postcss-extract-media-query).

The eventual goal for me is to be able to write a custom transform that lets us write something like

```css
@media (breakpoints: md, lg) {
  .flex {
    display: flex;
  }
}
```

with the output

```css
// styles.css
.flex { display: flex }

// styles_md.css
.md\:flex { display: flex }

// styles_lg.css
.lg\:flex { display: flex }
```
