### ISSUE TITLE
css variable declaration calc minification

### ISSUE THREAD

**Issue by MoritzLoewenstein** [parcel-bundler/lightningcss#506]
Currently, the following calc expression will not be minified:
```css
:root {
    --foo: calc(10px + 20px);
}
```
I know that it would break js code that relies on the computed style value for that property.

I will consider trying to implement this if there is a chance that it will me merged (as an opt-in option),
otherwise feel free to close :)
