### ISSUE TITLE
analyzeDependencies not work in bundle api?

### ISSUE THREAD

**Issue by noyobo** [parcel-bundler/lightningcss#514]
```css
// a.css
@import url('./b.css');

.a {
    color: red;
}
```

```js
const result = await bundle({
    filename: 'a.css',
    sourceMap: true,
    analyzeDependencies: true,
  });

console.log(result.dependencies) // []
```

lightningcss v1.21.0
