### ISSUE TITLE
`-webkit-` prefix removed from `backdrop-filter` even though Safari needs it

### ISSUE THREAD

**Issue by schuetzm** [parcel-bundler/lightningcss#537]
Safari doesn't support unprefixed `backdrop-filter`:
https://caniuse.com/css-backdrop-filter

Unfortunately, LightningCSS removes the necessary `-webkit-` prefix when both the prefixed and the normal version are used:
[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A1048576%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22body%20%7B%5Cn%20%20-webkit-backdrop-filter%3A%20blur(20px)%3B%5Cn%20%20backdrop-filter%3A%20blur(20px)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Funnily enough, if there's only an unprefixed `backdrop-filter`, it outputs both the prefixed and the unprefixed version:
[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A1048576%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22body%20%7B%5Cn%20%20backdrop-filter%3A%20blur(20px)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

I would expect both inputs to result in the same output including both the prefixed and unprefixed declaration.

**Comment by christianmartinnies** [comment]
I observe the exact opposite behaviour as it is added twice after a build.

Source:
```css
dialog::backdrop {
  opacity: 1;
  backdrop-filter: blur(0.125rem);
}
```

Build:
```css
dialog::backdrop {
  opacity: 1;
  -webkit-backdrop-filter: blur(0.125rem);
  -webkit-backdrop-filter: blur(0.125rem);
  backdrop-filter: blur(0.125rem);
}
```

**Comment by LeoniePhiline** [comment]
I posted in #403 but maybe this fits here better? It looks like there's multiple bugs related to `-webkit-backdrop-filter`.

Re-post from #403 (dear maintainers, please let me know which one I should delete, if any!):

I get `@supports` rules with `-webkit-backdrop-filter` duplicated.
Also, existing `-webkit-backdrop-filter` CSS rules (not `@supports` statements) are removed.

# Repro

lightningcss 1.21.1 and lightningcss-cli 1.21.5 mis-transform the following:

## Source

This source was generated by parcel with the `--no-optimize` flag.

```css
@supports (
  (-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))
) {
  :root {
    --some-color: #000000e6;
  }
}

.cc-bottom {
  -webkit-backdrop-filter: saturate(250%) blur(8px);
  backdrop-filter: saturate(250%) blur(8px);
}

.transition {
  transition-property:
    color,
    background-color,
    border-color,
    text-decoration-color,
    fill,
    stroke,
    opacity,
    box-shadow,
    transform,
    filter,
    -webkit-backdrop-filter,
    backdrop-filter;
}

@supports (
  (-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))
) {
  .supports-bg-filter\:bg-blur-saturate {
    -webkit-backdrop-filter: saturate(250%) blur(8px);
    backdrop-filter: saturate(250%) blur(8px);
  }
}
```

Into this result:

## Result

This output was generated by lightningcss-cli by invoking `pnpm exec lightningcss --targets 'defaults' input.css -o output.css`

```css
@supports ((-webkit-backdrop-filter: blur(8px))) or ((-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))) {
  :root {
    --some-color: rgba(0, 0, 0, .9);
  }
}

.cc-bottom {
  backdrop-filter: saturate(250%) blur(8px);
}

.transition {
  transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, -webkit-backdrop-filter, -webkit-backdrop-filter, backdrop-filter;
}

@supports ((-webkit-backdrop-filter: blur(8px))) or ((-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))) {
  .supports-bg-filter\:bg-blur-saturate {
    backdrop-filter: saturate(250%) blur(8px);
  }
}
```

## Notes:

- `@supports`: `(-webkit-backdrop-filter: blur(8px)) or (backdrop-filter: blur(8px))` has the webkit prefixed part duplicated.
- All `-webkit-backdrop-filter:` rules are removed.
