### ISSUE TITLE
Merging `:has` rules that can't be merged?

### ISSUE THREAD

**Issue by prscoelho** [parcel-bundler/lightningcss#548]
The following rules seem to get merged together:

```css
.tooltip.tooltip-open:before,
.tooltip.tooltip-open:after,
.tooltip:hover:before,
.tooltip:hover:after {
  opacity: 1;
  transition-delay: 75ms;
}

.tooltip:has(:focus-visible):after,
.tooltip:has(:focus-visible):before {
  opacity: 1;
  transition-delay: 75ms;
}
```
which minified results in:
```css
.tooltip.tooltip-open:after,
.tooltip.tooltip-open:before,
.tooltip:has(:focus-visible):after,
.tooltip:has(:focus-visible):before,
.tooltip:hover:after,
.tooltip:hover:before {
  opacity: 1;
  transition-delay: 75ms;
}
```

However, it seems like using :has() results in the [entire selector chain being invalidated on firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#syntax), breaking something that worked before minify.

**Comment by mayank99** [comment]
fwiw you can work around this by wrapping `:has` with `is`/`:where` which accept a [forgiving selector list](https://developer.mozilla.org/en-US/docs/Web/CSS/:is#forgiving_selector_parsing).

```css
.tooltip.tooltip-open:after,
.tooltip.tooltip-open:before,
.tooltip:is(:has(:focus-visible)):after,
.tooltip:is(:has(:focus-visible)):before,
.tooltip:hover:after,
.tooltip:hover:before {
  opacity: 1;
  transition-delay: 75ms;
}
```

maybe this is something lightningcss could do automatically when minifying
