### ISSUE TITLE
Removes spaces before colons accidentally

### ISSUE THREAD

**Issue by kemchenj** [parcel-bundler/lightningcss#557]
Hello, I noticed a bug where minifying CSS with LightningCSS can sometimes accidentally remove spaces before colons in selectors, changing the selector semantics.

For example, I had the following CSS:

```css
.toggle.toggle-close :first-child {
  top: 6px;
  transform:rotate(45deg)
}
```

The space before the colon indicates this should select any first child of an element with classes `toggle` and `toggle-close`.

However, after minification, the code became:

```css
.toggle.toggle-close:first-child{top:6px;transform:rotate(45deg)}
```

By accidentally removing the space before the colon, the selector now only matches elements that themselves have the classes `toggle` and `toggle-close` and are a first child.

Could you please take a look at this issue?

Thank you for your time and for developing LightningCSS! Let me know if any other details would be helpful.
