### ISSUE TITLE
incorrect minification with cascade layers

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#571]
https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40layer%20a%20%7B%7D%5Cn%40layer%20b%20%7B%7D%5Cn%5Cn%40layer%20b%20%7B%5Cn%20%20foo%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40layer%20a%20%7B%5Cn%20%20bar%20%7B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

-----

```css
@layer a {}
@layer b {}

@layer b {
  foo {
    color: red;
  }
}

@layer a {
  bar {
    color: green;
  }
}
```

Becomes :

```css
@layer b{foo{color:red}bar{color:green}}
```
