### ISSUE TITLE
Support leading type selector in nesting

### ISSUE THREAD

**Issue by valtlai** [parcel-bundler/lightningcss#576]
Firefox 117 supports the following:

```css
.foo {
  mark {
    background: lime;
  }

  main & {
    font-size: 2em;
  }
}
```

([CodePen demo](https://codepen.io/valtlai/pen/RwERwZw))

Other browsers don’t currently support a nested selector starting with a symbol, so the nesting selector `&` or the `:is()` pseudo-class is needed:

```css
.foo {
  & mark {
    background: lime;
  }

  :is(main) & {
    font-size: 2em;
  }
}
```

The CSSWG [removed this restriction](https://github.com/w3c/csswg-drafts/issues/7961#issuecomment-1514955984), but the other browser aren’t yet implemented/shipped this change.

Lightning CSS should apply these transformations, so the CSS authors can use a bare type selector at the start of the entire selector.
