### ISSUE TITLE
visitors: values aren't spaced out

### ISSUE THREAD

**Issue by robertmoura** [parcel-bundler/lightningcss#579]
I'm getting an issue when trying to create a custom Visitor where I try this:
```css
.example {
  border-radius: custom() 1px;
  border-radius: custom() var(--something);
  border-radius: custom() custom();
  border-radius: var(--something) custom();
}
```
and this is the output:
```css
.example {
  border-radius: inherit1px;
  border-radius: inheritvar(--something);
  border-radius: inheritinherit;
  border-radius: var(--something) inherit;
}
```
There is no whitespace between the values and I can't seem do this easily by adding spaces around the raw value either.
```javascript
{
  Function: {
    custom: () => ({
      raw: 'inherit',
    })
  }
}
```

[Reproduction](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.example%20%7B%5Cn%20%20border-radius%3A%20custom()%201px%3B%5Cn%20%20border-radius%3A%20custom()%20var(--something)%3B%5Cn%20%20border-radius%3A%20custom()%20custom()%3B%5Cn%20%20border-radius%3A%20var(--something)%20custom()%3B%5Cn%7D%5Cn%5Cn.example-work-around%20%7B%5Cn%20%20border-radius%3A%20customFixed()%201px%3B%5Cn%20%20border-radius%3A%20customFixed()%20var(--something)%3B%5Cn%20%20border-radius%3A%20customFixed()%20customFixed()%3B%5Cn%20%20border-radius%3A%20var(--something)%20customFixed()%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Atrue%2C%22visitor%22%3A%22%7B%5Cn%20%20Function%3A%20%7B%5Cn%20%20%20%20custom%3A%20()%20%3D%3E%20(%7B%5Cn%20%20%20%20%20%20raw%3A%20'inherit'%2C%5Cn%20%20%20%20%7D)%2C%5Cn%20%20%20%20customFixed%3A%20()%20%3D%3E%20(%7B%5Cn%20%20%20%20%20%20raw%3A%20'var(--noop%2C%20inherit)'%2C%5Cn%20%20%20%20%7D)%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Is there a way around this? Or is this a bug? Would love to be able to use custom functions sort of like `var`.

As a work around, I'm wrapping the raw value in an invalid var with a fallback 😊
```css
{
  Function: {
    custom: () => ({
      raw: 'var(--noop, inherit)',
    })
  }
}
```
