### ISSUE TITLE
Inconsistent  CSS variables rules optimization

### ISSUE THREAD

**Issue by scebotari66** [parcel-bundler/lightningcss#580]
Given the following CSS:
```css
.foo {
  color: red;
  color: var(--my-red);
  background-color: blue;
  background-color: var(--my-blue);
}
```

I get this output:
```css
.foo {
  color: var(--my-red);
  background-color: #00f;
  background-color: var(--my-blue);
}
```
I would also expect only the CSS variables `background-color` rule version to be kept, like it is the case with `color`. Is this a bug?

**Comment by devongovett** [comment]
Yeah we could probably make this line conditional depending what other background-related properties have been seen. https://github.com/parcel-bundler/lightningcss/blob/9b3e6f425b1132243930737f306cb864b7b892d0/src/properties/background.rs#L897

**Comment by yisibl** [comment]
The `revert-rule` keyword has been implemented in the [CSS specification](https://github.com/w3c/csswg-drafts/pull/12992) and in [Chrome](chromium-review.googlesource.com/c/chromium/src/+/6884901).

Therefore, the current property merging behavior is no longer safe. Especially since CSS will introduce more revert functionality in the future, e.g. [`first-valid()`](https://www.w3.org/TR/2024/WD-css-values-5-20241111/#first-valid).

## input

```css
.test {
  font-size: 36px;
  color: green;
}
.test {
  color: var(--foo, revert-rule);
}
```

## lightningcss output

```css
.test {
  color: var(--foo, revert-rule);
  font-size: 36px;
}
```

## Demo

```html
data:text/html;charset=UTF-8,<!DOCTYPE html>
<style>
.test {
  font-size: 36px;
  color: green;
}
.test {
  color: var(--foo, revert-rule);
}

.lightningcss {
  color: var(--foo, revert-rule);
  font-size: 36px;
}
</style>

<div class="test">This text should be a green.</div>
<div class="lightningcss">This text should be a green?</div>
```

<img width="1002" height="250" alt="Image" src="https://github.com/user-attachments/assets/5c1a232f-18e4-4c54-9f30-839aaab01d51" />
