### ISSUE TITLE
Custom media queries and cascade layers issue

### ISSUE THREAD

**Issue by stevendierick** [parcel-bundler/lightningcss#582]
There seems to be a problem when a custom media query is defined inside a cascade layer.

I'm using Lightning CSS (1.21.7) with Vite (4.4.9). Also tested it in the Lightning CSS Playground which has the same issues.

I've also tested this with PostCSS + PostCSS Preset Env which don't have the same issues.

---

This will work fine:

```css
@custom-media --modern (color), (hover);

@media (--modern) and (width > 1024px) {
  .a {
    color: green;
  }
}
```

This will not work and throw an error `Custom media query --modern is not defined`:

```css
@layer theme {
  @custom-media --modern (color), (hover);

  @media (--modern) and (width > 1024px) {
    .a {
      color: green;
    }
  }
}
```

It will work if you define the custom media query outside the layer:

```css
@custom-media --modern (color), (hover);

@layer theme {
  @media (--modern) and (width > 1024px) {
    .a {
      color: green;
    }
  }
}
```

The same issue happens if you would import a CSS file into a layer.

This will not work:

**style.css**
```css
@import url('theme-styling.css') layer(theme);
```

**theme-styling.css**
```css
@custom-media --modern (color), (hover);

@media (--modern) and (width > 1024px) {
  .a {
    color: green;
  }
}
```

But it will work if you define the custom media query after the import and outside a layer:

**style.css**
```css
@import url('theme-styling.css') layer(theme);

@custom-media --modern (color), (hover);
```

**theme-styling.css**
```css
@media (--modern) and (width > 1024px) {
  .a {
    color: green;
  }
}
```
