### ISSUE TITLE
How to get the original CSS selectors?

### ISSUE THREAD

**Issue by ModyQyW** [parcel-bundler/lightningcss#587]
Hi. Thanks for your great work first!

I am trying to build the lightningcss version of a postcss plugin, which uses original CSS selectors inside. I wonder, how to get the original CSS selectors in a lightningcss plugin? If I can get the original CSS selectors, the job will be much easier.

**Comment by devongovett** [comment]
Not sure what you mean by "original" CSS selectors. Could you elaborate?

**Comment by ModyQyW** [comment]
Thanks for your reply. 🙏

Here is an example.

Assume I have a CSS file like below.

```css
'uni-image>img{-webkit-touch-callout:none;-webkit-user-select:none;user-select:none;display:block;position:absolute;top:0;left:0;width:100%;height:100%;opacity:0}'
```

In my postcss plugin, I use `node.selector` (original selector) to generate a new selector. In this example,  I get `uni-image>img` as `node.selector` (original selector).

<img width="616" alt="image" src="https://github.com/parcel-bundler/lightningcss/assets/31850793/055cc3e2-0f6a-402b-8d3b-f4515d166ca0">

In my lightningcss plugin, I try to use Selector Visitor to generate a new selector, but I get an array like below.

```js
[
  { type: 'type', name: 'uni-image' },
  { type: 'combinator', value: 'child' },
  { type: 'type', name: 'img' }
]
```

It is kind of hard to reuse my postcss plugin logic because it operates strings directly. So I wonder how to convert the array into a string like `uni-image>img`? Do I need to parse the array manually?
