### ISSUE TITLE
Issue with Overriding CSS Variables

### ISSUE THREAD

**Issue by dev-mohanraj** [parcel-bundler/lightningcss#589]
Hi,

I'm working on a project where I'd like to utilize LightningCSS to minify my CSS code. However, I've encountered an issue that I'd like to describe below.

I've defined a CSS variable called --width-context with a default value of 100%. I've used this variable in the width property like so: width: var(--width-context). However, even when I change --width-context to 50% at runtime, the width property still retains 100%.

Base Style:

```css
.card {
  --width-context: 100%;
}
``` 

Card Style:

```css
.overridecard {
  width: var(--width-context, 100%);
}
``` 

I have a theming configuration that allows me to change various properties of the cards, such as width, height, color, etc.

Overriding the Style:

```css
<style type="text/css">
.card {
  --width-context: 50%;
  }
</style>
``` 

Despite changing the value of the --width-context variable in the .body class, it appears that the variable value isn't being applied as expected.

If you could provide more details or context, I'd be happy to help you resolve this issue.
