### ISSUE TITLE
Support transforming oklab/oklch functions with variables in them

### ISSUE THREAD

**Issue by brc-dd** [parcel-bundler/lightningcss#592]
For example:

```css
.text-red-200 {
  --tw-text-opacity: 1;
  color: oklch(92.19% 0.04 20 / var(--tw-text-opacity));
}
```

can be transpiled to something like this: (similar to how [postcss-oklab-function](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-oklab-function) does)

```css
.text-red-200 {
  --tw-text-opacity: 1;
  color: rgba(255, 219, 218, var(--tw-text-opacity));
}

@supports (color: color(display-p3 0 0 0)) and (top: var(--f)) {
  .text-red-200 {
    color: color(display-p3 0.9775 0.86513 0.8587 / var(--tw-text-opacity));
  }
}

@supports (color: oklch(0% 0 0)) and (top: var(--f)) {
  .text-red-200 {
    color: oklch(92.19% 0.04 20 / var(--tw-text-opacity));
  }
}
```
