### ISSUE TITLE
`margin-inline-start` equals to `margin-inline-end` shouldn't be deleted

### ISSUE THREAD

**Issue by vollowx** [parcel-bundler/lightningcss#594]
I'm currently using these code to move the position of icon inside a button components.

```css
::slotted([slot='icon']) {
  margin-inline-end: 8px;
  margin-inline-start: -8px;
}
::slotted([slot='trailingicon']) {
  margin-inline-end: -8px;
  margin-inline-start: 8px;
}
:host([variant='text']) ::slotted([slot='icon']) {
  margin-inline-start: 0px;
}
:host([variant='text']) ::slotted([slot='trailingicon']) {
  margin-inline-end: 0px;
}
```

Although the `margin-inline-start` = `margin-inline-end`, they do make the position changed, so they're not useless and shouldn't be deleted while `lightningcss` removes them.
