### ISSUE TITLE
Minify CSS variable fallbacks

### ISSUE THREAD

**Issue by KTibow** [parcel-bundler/lightningcss#601]
Input:
```css
#foo {
  color: white;
}
#bar {
  color: var(--c, white);
}
```
Current output:
```css
#foo{color:#fff}#bar{color:var(--c,white)}
```
Expected output:
```css
#foo{color:#fff}#bar{color:var(--c,#fff)}
```
