### ISSUE TITLE
Minify fallback fallbacks for CSS variables

### ISSUE THREAD

**Issue by KTibow** [parcel-bundler/lightningcss#603]
In
```css
#foo {
  color: #f00;
  color: var(--c, #f00);
}
```
either transform it to
```css
#foo {
  color: #f00;
  color: var(--c);
}
```
or transform it to
```css
#foo {
  color: var(--c, #f00);
}
```
(The first one should have the exact same behavior as before, I think the second one has different behavior, so maybe don't do the second one or have a setting for that)
