### ISSUE TITLE
`@apply` gets messed up

### ISSUE THREAD

**Issue by KTibow** [parcel-bundler/lightningcss#605]
Context: CSS that will be used in a ShadyCSS environment
Repro:
![image](https://github.com/parcel-bundler/lightningcss/assets/10727862/3a803e5c-952c-4d23-930b-73b49ff97d74)
(It needs to have a target set for it to mess up)

**Comment by pascalduez** [comment]
I'm surprised the ShadyCSS docs does not seem to mention that `@apply` is abandoned for a long time now.

**Comment by KTibow** [comment]
Ah - well the thing is that I'm trying to add LCSS to a project that has dependencies on a bunch of Material 2 components, which use `@apply` for typography, so it wouldn't be that easy to remove. I tried to see if I could get this to work using a custom visitor or at rule before filing this issue, but I failed.

**Comment by pascalduez** [comment]
If I understand correctly, you need the `@apply` rule to be left untouched since it will be polyfilled in browser. 
So even adding [another built step](https://github.com/pascalduez/postcss-apply) before LCSS is not an option.

**Comment by devongovett** [comment]
I do not consider this a bug. `@apply` is not a standard at-rule, so there's no way Lightning CSS can know what to do with it. What you're seeing here is the result of the nesting transform, which un-nests rules as expected in older browsers. If you use the `exclude` option to turn of the `Nesting` feature, you can see the `@apply` is preserved inside the style rule. [Example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A1%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20color%3A%20red%3B%5Cn%20%20%40apply%20paper-thingy%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) Performing exceptions like this automatically is out of scope for Lightning CSS.

**Comment by KTibow** [comment]
Okay, thanks for explaining why it does that.
(FYI you could close this as "won't fix")

**Comment by KTibow** [comment]
Now the playground is showing some weird behavior.
Input:
```css
.foo:is(:active, :focus-visible) {
  background: yellow;
  @apply hi;
}
```
Output (target Chrome 50):
```css
.foo:-webkit-any(:active,:focus-visible){background:#ff0}@apply hi;.foo:is(:active,:focus-visible){background:#ff0}@apply hi;
```
Output (exclude nesting, target Chrome 50):
```css
.foo:is(:active,:focus-visible){background:#ff0;@apply hi;}
```
Output (include is selector, exclude nesting, target Chrome 50, desired behavior):
```css
.foo:-webkit-any(:active,:focus-visible){background:#ff0;@apply hi;}.foo:is(:active,:focus-visible){background:#ff0;@apply hi;}
```
Why did excluding nesting exclude the is selector transform?
