### ISSUE TITLE
single line comments //

### ISSUE THREAD

**Issue by tasiotas** [parcel-bundler/lightningcss#624]
Hi,

Seems like single line comments are not supported by Lightning CSS.
SCSS does specify it as valid comment
https://sass-lang.com/documentation/syntax/comments/

What should we do? 
1. Switch to multiline comments even for single line? /*  */
2. Its not trivial to set VSCode to use multiline comments in scss files. 
3. Will Lightning CSS support single line comments?

```scss
  // body padding
  --body--padding--x: 1rem;
  @screen lg {
    --body--padding--x: 2rem;
  }
```

```
15 |  
16 |    // body padding
17 |    --body--padding--x: 1rem;
   |                             ^
18 |    @screen lg {
19 |      --body--padding--x: 2rem;
```

```
ERROR  Invalid empty selector
```
