### ISSUE TITLE
scss modules: reference @keyframes identifier in css variables

### ISSUE THREAD

**Issue by florianloechle** [parcel-bundler/lightningcss#627]
Hi, I'm trying to get the following to work but with no luck:

```scss
.root {
  --animation-name: fade-in
}

@keyframes fade-in {
  from { opacity: 0; }
  to { opacity: 1; }
}
```

Is it possible to get the hashed keyframe identifier in the css variable? It currently compiles to:

```scss
.root {
  --animation-name: fade-in
}

@keyframes FQ4BKa-fade-in {
  from { opacity: 0; }
  to { opacity: 1; }
}
```
I'm using the version **1.22.1**. 

Help would be appreciated, thanks for this awesome project!
