### ISSUE TITLE
CSS module import missing exports 

### ISSUE THREAD

**Issue by megheaiulian** [parcel-bundler/lightningcss#638]
Using css modules and imports if we have a file btn.css:

```css
.btn {
 color: red;
}
```

and in other.module.css
```css
  @import "btn.css";
 .btn {
   font-size: 12px;
 }
```
I would expect the result to be CSS module that contains both declarations under one selector: 
```css
 .axxaxa_btn {
  color: red;
  font-size: 12px;
}
```

The way it currently works and is tested in https://github.com/parcel-bundler/lightningcss/blob/master/src/bundler.rs#L1759 the styles from the imported file are scoped and inlined but you can't do anything with them. 
Why even import them then ?

**Comment by devongovett** [comment]
if you want to combine them, then you should use the `composes` property:

```css
.btn {
  composes: btw from './btn.css';
  font-size: 12px;
}
```
