### ISSUE TITLE
ERROR: Unexpected token CurlyBracketBlock

### ISSUE THREAD

**Issue by monako97** [parcel-bundler/lightningcss#642]
```css
:root {
    background-color: var(--bg);
}

html,
body {
    inline-size: 100vi;
    font-size: var(--font-size);
    font-family: var(--font-family);
    color: var(--text-color, rgb(0 0 0 / 65%));
    transition-duration: 0.3s;
    transition-property: background-color, color;
    transition-timing-function: cubic-bezier(0.94, -0.1, 0.1, 1.2);
}

#root {
    display: flex;
    flex-wrap: wrap;
    -webkit-overflow-scrolling: touch;
}

#root > main {
    animation: route-in var(--transition-duration, 0.3s);
}

n-provider {
    display: flex;
    inline-size: 100vi;
}

.site-doc-main {
    margin-block-start: 16px;
    inline-size: calc(100% - 288px);
}

.site-page-view {
    box-sizing: border-box;
    margin: 16px auto 0;
    min-block-size: calc(100vb - 132px);

    n-md::part(body) > div:empty {
        margin: 0;
        padding: 0;
        background-color: transparent;
        backdrop-filter: none;
        box-shadow: none;
        pointer-events: none;
    }

    n-md::part(toc) {
        inset-block-start: 16px;
    }

    n-md::part(body) {
        tr > th,
        tr > td {
            &:last-child,
            &:nth-last-child(2) {
                min-inline-size: 45px;
            }
        }
    }
}

body {
    overflow-x: hidden;
}

body::before {
    position: fixed;
    inset-block-start: 0;
    z-index: 1;
    display: block;
    inline-size: 100vi;
    block-size: 100px;
    background: linear-gradient(
        124deg,
        #f44336,
        #e91e63,
        #9c27b0,
        #673ab7,
        #3f51b5,
        #2196f3,
        #03a9f4,
        #00bcd4,
        #009688,
        #4caf50,
        #8bc34a,
        #cddc39,
        #ffeb3b,
        #ffc107,
        #ff9800,
        #ff5722
    );
    background-size: 800% 800%;
    opacity: 0.2;
    content: '';
    transform: translateY(-100px);
    animation: color-hue 15s var(--transition-timing-function) infinite;
}

.n-site-bg {
    position: fixed;
    inset-block-start: 50%;
    inset-inline-start: 50%;
    z-index: -1;
    inline-size: 100vi;
    block-size: 100vb;
    background: linear-gradient(#673ab7, transparent), linear-gradient(90deg, #ff5722, transparent),
        linear-gradient(-90deg, #8bc34a, transparent);
    transform: translate(-50%, -50%);
    background-blend-mode: screen;
    animation: color-hue 15s infinite alternate linear;
    pointer-events: none;
    opacity: 0.05;
}

@keyframes route-in {
    from {
        transform: translate3d(0, 16px, 0);
        opacity: 0;
    }

    to {
        transform: translate3d(0, 0, 0);
        opacity: 1;
    }
}

@keyframes color-hue {
    100% {
        filter: hue-rotate(360deg);
    }
}

@media screen and (width <= 1100px) {
    .site-doc-main {
        inline-size: calc(100% - 116px);
    }
}
```

ERROR: Unexpected token CurlyBracketBlock
<img width="994" alt="截屏2023-12-08 17 20 00" src="https://github.com/parcel-bundler/lightningcss/assets/41319447/6c5e5a5c-5a86-4c0d-963e-d17069a9d9a0">
<img width="994" alt="截屏2023-12-08 17 20 00" src="https://github.com/parcel-bundler/lightningcss/assets/41319447/8f5441d1-4c9f-45e4-8955-2c8afb8c1010">
