### ISSUE TITLE
Minification of html & :host when using browserslist

### ISSUE THREAD

**Issue by sdavids** [parcel-bundler/lightningcss#644]
I am unsure if this is a bug or correct.

```shell
$ npx lightningcss --version       
lightningcss 1.0.0-alpha.51
$ npm list --depth=0 | grep lightningcss-cli
└── lightningcss-cli@1.22.1
```

.browserslistrc 
```
defaults
```

test.css
```css
html {
  line-height: 1;
}

:host {
  line-height: 1;
}
```

```shell
$ npx lightningcss --minify test.css               
html,:host{line-height:1}
```

```shell
$ npx lightningcss --minify test.css --browserslist
html{line-height:1}:host{line-height:1}
```
