### ISSUE TITLE
Rule placed in wrong layer (and correct layer is missing)

### ISSUE THREAD

**Issue by thecrypticace** [parcel-bundler/lightningcss#653]
An empty layer block causes Lightning CSS to place classes in the wrong layer. For example, the following incorrectly places `.baz` in the `utilities` layer and is also missing the `components` layer entirely: [Playground Link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%2F*%20You%20can%20comment%20this%20layer%20to%20%5C%22fix%5C%22%20the%20output%20*%2F%5Cn%40layer%20components%20%7B%7D%5Cn%5Cn%40layer%20utilities%20%7B%5Cn%20%20.foo%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40layer%20components%20%7B%5Cn%20%20.baz%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40layer%20utilities%20%7B%5Cn%20%20.bar%20%7B%5Cn%20%20%20%20color%3A%20blue%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Input:

```css
/* You can comment this layer to "fix" the output */
@layer components {}

@layer utilities {
  .foo {
    color: red;
  }
}

@layer components {
  .baz {
    color: red;
  }
}

@layer utilities {
  .bar {
    color: blue;
  }
}
```

Expected:
```css
@layer utilities {
  .foo {
    color: red;
  }

  .bar {
    color: #00f;
  }
}

@layer components {
  .baz {
    color: red;
  }
}
```

Actual:
```css
@layer utilities {
  .foo, .baz {
    color: red;
  }

  .bar {
    color: #00f;
  }
}
```
