### ISSUE TITLE
`@property` registration with universal syntax doesn't support empty `initial-value`

### ISSUE THREAD

**Issue by thecrypticace** [parcel-bundler/lightningcss#654]
The following CSS produces a parse error but should not.

The [CSS spec](https://drafts.css-houdini.org/css-properties-values-api-1/#initial-value-descriptor) originally listed the value type for `initial-value` as `<declaration-value>` which meant a value was required but that was inconsistent with the behavior of actual custom property declarations. It was changed, as of August 2023, to `<declaration-value>?` which permits empty values and spaces — the same as custom properties.

Chrome already handles this appropriately but it appears that Safari has not yet been updated with the spec change. Aside: the JS API can be used to work around it in Safari as it works correctly.

[Playground Link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40property%20--my-x%20%7B%5Ct%5Cn%20%20syntax%3A%20%5C%22*%5C%22%3B%5Ct%5Cn%20%20inherits%3A%20false%3B%5Ct%5Cn%5Cn%20%20%2F*%20This%20doesn't%20parse%20*%2F%5Cn%20%20initial-value%3A%3B%5Ct%5Cn%7D%5Ct%5Cn%5Cn%40property%20--my-y%20%7B%5Ct%5Cn%20%20syntax%3A%20%5C%22*%5C%22%3B%5Ct%5Cn%20%20inherits%3A%20false%3B%5Ct%5Cn%20%20%5Cn%20%20%2F*%20Nor%20does%20this%20*%2F%5Cn%20%20initial-value%3A_%3B%5Ct%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Input:
```css
@property --my-x {	
  syntax: "*";	
  inherits: false;	

  /* This doesn't parse */
  initial-value:;	
}	

@property --my-y {	
  syntax: "*";	
  inherits: false;	
  
  /* Nor does this */
  initial-value: ;	
}
```

Expected:
```css
@property --my-x {
  syntax: "*";
  inherits: false;
  initial-value:;
}

@property --my-y {
  syntax: "*";
  inherits: false;
  initial-value: ;
}
```

Actual:
```css
/* ERROR: Unexpected end of input */
```
