### ISSUE TITLE
`@layer`s nested inside style rules are not merged

### ISSUE THREAD

**Issue by thecrypticace** [parcel-bundler/lightningcss#655]
When nesting an `@layer` inside a style rule it's properly lifted but multiple layers with the same name are not merged — whether minified or not. This merging typically happens even when not minifying but I think it would be acceptable if, to fix it, minification was required:

[Playground Link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20%40layer%20utilities%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.baz%20%7B%5Cn%20%20%40layer%20components%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.bar%20%7B%5Cn%20%20%40layer%20utilities%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Input:
```css
.foo {
  @layer utilities {
    color: red;
  }
}

.baz {
  @layer components {
    color: red;
  }
}

.bar {
  @layer utilities {
    color: red;
  }
}
```

Expected:
```css
@layer utilities {
  .foo, .bar {
    color: red;
  }
}

@layer components {
  .baz {
    color: red;
  }
}
```

Actual:
```css
@layer utilities {
  .foo {
    color: red;
  }
}

@layer components {
  .baz {
    color: red;
  }
}

@layer utilities {
  .bar {
    color: red;
  }
}
```
