### ISSUE TITLE
`@property` rules should be de-duplicated at the top-level

### ISSUE THREAD

**Issue by thecrypticace** [parcel-bundler/lightningcss#656]
Lightning CSS does not currently — but should — merge `@property` declarations for the same property when at the top level of a stylesheet. And could, potentially, do so when multiple are found at the "same" level. For example, if the same property registration existed more than once inside equivalent media queries. According to [the spec](https://drafts.css-houdini.org/css-properties-values-api/#at-property-rule), for a given property, the latest `@property` rule in stylesheet order wins.

Notes:
1. For top-level at least, moving all `@property` declarations to the beginning seems like a sensible thing to do. But this is obviously not a necessity.
2. Lightning CSS seems to treat `@property` inside of `@media` and `@layer` as a semi-raw token stream instead of validating and formatting it appropriately.

[Playground Link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7536640%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40property%20--tw-translate-x%20%7B%5Cn%20%20syntax%3A%20'%3Clength%3E'%3B%5Cn%20%20inherits%3A%20false%3B%5Cn%20%20initial-value%3A%200%3B%5Cn%7D%5Cn%5Cn%40layer%20utilities%20%7B%5Cn%20%20.translate-x-1%20%7B%5Cn%20%20%20%20--tw-translate-x%3A%200.25rem%3B%5Cn%20%20%20%20translate%3A%20var(--tw-translate-x)%20var(--tw-translate-y)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%2F*%20This%20is%20a%20duplicate%20of%20the%20above%20rule%20—%20but%20even%20if%20the%20values%20were%20different%20this%20one%20would%20win%20*%2F%5Cn%40property%20--tw-translate-x%20%7B%5Cn%20%20syntax%3A%20'%3Clength%3E'%3B%5Cn%20%20inherits%3A%20false%3B%5Cn%20%20initial-value%3A%200%3B%5Cn%7D%5Cn%5Cn%40layer%20utilities%20%7B%5Cn%20%20.translate-x-4%20%7B%5Cn%20%20%20%20--tw-translate-x%3A%201rem%3B%5Cn%20%20%20%20translate%3A%20var(--tw-translate-x)%20var(--tw-translate-y)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40property%20--tw-translate-y%20%7B%5Cn%20%20syntax%3A%20'%3Clength%3E'%3B%5Cn%20%20inherits%3A%20false%3B%5Cn%20%20initial-value%3A%200%3B%5Cn%7D%5Cn%5Cn%40layer%20utilities%20%7B%5Cn%20%20.translate-y-2%20%7B%5Cn%20%20%20%20--tw-translate-y%3A%200.5rem%3B%5Cn%20%20%20%20translate%3A%20var(--tw-translate-x)%20var(--tw-translate-y)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40property%20--tw-translate-z%20%7B%5Cn%20%20syntax%3A%20%5C%22%3Clength%3E%5C%22%3B%5Cn%20%20inherits%3A%20false%3B%5Cn%20%20initial-value%3A%200px%3B%5Cn%7D%5Cn%5Cn%40media%20screen%20and%20(width%20%3E%3D%20768px)%20%7B%5Cn%20%20%40property%20--tw-translate-z%20%7B%5Cn%20%20%20%20syntax%3A%20%5C%22%3Clength%3E%5C%22%3B%5Cn%20%20%20%20inherits%3A%20false%3B%5Cn%20%20%20%20initial-value%3A%200px%3B%5Cn%20%20%7D%5Cn%5Cn%20%20%40property%20--tw-translate-z%20%7B%5Cn%20%20%20%20syntax%3A%20%5C%22%3Clength%3E%5C%22%3B%5Cn%20%20%20%20inherits%3A%20false%3B%5Cn%20%20%20%20initial-value%3A%200px%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Input:
```css
@property --tw-translate-x {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@layer utilities {
  .translate-x-1 {
    --tw-translate-x: 0.25rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }
}

/* This is a duplicate of the above rule — but even if the values were different this one would win */
@property --tw-translate-x {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@layer utilities {
  .translate-x-4 {
    --tw-translate-x: 1rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }
}

@property --tw-translate-y {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@layer utilities {
  .translate-y-2 {
    --tw-translate-y: 0.5rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }
}

@property --tw-translate-z {
  syntax: "<length>";
  inherits: false;
  initial-value: 0px;
}

@media screen and (width >= 768px) {
  @property --tw-translate-z {
    syntax: "<length>";
    inherits: false;
    initial-value: 0px;
  }

  @property --tw-translate-z {
    syntax: "<length>";
    inherits: false;
    initial-value: 0px;
  }
}
```

Expected:
```css
@property --tw-translate-x {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@property --tw-translate-y {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@property --tw-translate-z {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@media screen and (width >= 768px) {
  @property --tw-translate-z {
    syntax: "<length>";
    inherits: false;
    initial-value: 0px;
  }
}

@layer utilities {
  .translate-x-1 {
    --tw-translate-x: .25rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }

  .translate-x-4 {
    --tw-translate-x: 1rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }

  .translate-y-2 {
    --tw-translate-y: .5rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }
}
```

Actual:
```css
@property --tw-translate-x {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@layer utilities {
  .translate-x-1 {
    --tw-translate-x: .25rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }

  .translate-x-4 {
    --tw-translate-x: 1rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }

  .translate-y-2 {
    --tw-translate-y: .5rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }
}

@property --tw-translate-x {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@property --tw-translate-y {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@property --tw-translate-z {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@media screen and (width >= 768px) {
  @property --tw-translate-z {
    syntax: "<length>"; inherits: false; initial-value: 0px;
  }

  @property --tw-translate-z {
    syntax: "<length>"; inherits: false; initial-value: 0px;
  }
}
```
