### ISSUE TITLE
Option to disable logical properties transpilation

### ISSUE THREAD

**Issue by azat-io** [parcel-bundler/lightningcss#663]
Hi!

When I write this code:

```css
.select {
  inset-inline: 0;
}
```

I get this:

```css
.select:not(
    :-webkit-any(
        :lang(ae),
        :lang(ar),
        :lang(arc),
        :lang(bcc),
        :lang(bqi),
        :lang(ckb),
        :lang(dv),
        :lang(fa),
        :lang(glk),
        :lang(he),
        :lang(ku),
        :lang(mzn),
        :lang(nqo),
        :lang(pnb),
        :lang(ps),
        :lang(sd),
        :lang(ug),
        :lang(ur),
        :lang(yi)
      )
  ) {
  right: 0;
}
.select:not(
    :-moz-any(
        :lang(ae),
        :lang(ar),
        :lang(arc),
        :lang(bcc),
        :lang(bqi),
        :lang(ckb),
        :lang(dv),
        :lang(fa),
        :lang(glk),
        :lang(he),
        :lang(ku),
        :lang(mzn),
        :lang(nqo),
        :lang(pnb),
        :lang(ps),
        :lang(sd),
        :lang(ug),
        :lang(ur),
        :lang(yi)
      )
  ) {
  right: 0;
}
.select:not(
    :is(
        :lang(ae),
        :lang(ar),
        :lang(arc),
        :lang(bcc),
        :lang(bqi),
        :lang(ckb),
        :lang(dv),
        :lang(fa),
        :lang(glk),
        :lang(he),
        :lang(ku),
        :lang(mzn),
        :lang(nqo),
        :lang(pnb),
        :lang(ps),
        :lang(sd),
        :lang(ug),
        :lang(ur),
        :lang(yi)
      )
  ) {
  right: 0;
}
.select:-webkit-any(
    :lang(ae),
    :lang(ar),
    :lang(arc),
    :lang(bcc),
    :lang(bqi),
    :lang(ckb),
    :lang(dv),
    :lang(fa),
    :lang(glk),
    :lang(he),
    :lang(ku),
    :lang(mzn),
    :lang(nqo),
    :lang(pnb),
    :lang(ps),
    :lang(sd),
    :lang(ug),
    :lang(ur),
    :lang(yi)
  ) {
  left: 0;
}
.select:-moz-any(
    :lang(ae),
    :lang(ar),
    :lang(arc),
    :lang(bcc),
    :lang(bqi),
    :lang(ckb),
    :lang(dv),
    :lang(fa),
    :lang(glk),
    :lang(he),
    :lang(ku),
    :lang(mzn),
    :lang(nqo),
    :lang(pnb),
    :lang(ps),
    :lang(sd),
    :lang(ug),
    :lang(ur),
    :lang(yi)
  ) {
  left: 0;
}
.select:is(
    :lang(ae),
    :lang(ar),
    :lang(arc),
    :lang(bcc),
    :lang(bqi),
    :lang(ckb),
    :lang(dv),
    :lang(fa),
    :lang(glk),
    :lang(he),
    :lang(ku),
    :lang(mzn),
    :lang(nqo),
    :lang(pnb),
    :lang(ps),
    :lang(sd),
    :lang(ug),
    :lang(ur),
    :lang(yi)
  ) {
  left: 0;
}
```

Is there any way to disable transpilation of logical properties? They are well-supported by browsers and I don't need it.
