### ISSUE TITLE
Doesn't error on invalid property or value

### ISSUE THREAD

**Issue by KevinBatdorf** [parcel-bundler/lightningcss#680]
Neither of these error but I would expect them to. If it's not meant to error, would you recommend some way to approach getting that information? 

For example, I can use the `Declaration` visitor and get the property/value but not the location. Thanks

```css
p {
  foo: blue;
}
p {
  color: bluezzzz;
}
```
