### ISSUE TITLE
Combination of `transition` and `transition-property` is being built into a longer form

### ISSUE THREAD

**Issue by dyc3** [parcel-bundler/lightningcss#705]
Certain combinations of `transition` properties get built into a longer form. 

Example input:

```css
.foo {
  transition: 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  transition-property: height, width, transform, max-width, left, right, top, bottom, box-shadow;
}
```
[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20transition%3A%20all%200.2s%20cubic-bezier(0.4%2C%200%2C%200.2%2C%201)%3B%5Cn%20%20transition-property%3A%20height%2C%20width%2C%20transform%2C%20max-width%2C%20left%2C%20right%2C%20top%2C%20bottom%2C%20box-shadow%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.24.1%22%7D)

If I could get a couple code pointers, I'd love to contribute a fix for it.
