### ISSUE TITLE
how can I fixed it

### ISSUE THREAD

**Issue by ckken** [parcel-bundler/lightningcss#707]
```css
video {
    display: inline-block;
    *display: inline;
    *zoom: 1;
}
```
it work for postcss

**Comment by ckken** [comment]
use errorRecovery:true it pass compiled,but 
```css
.p {
    color: red;
    *margin: 2px;
}
```
the color doesn't work
```css
.p {
    *margin: 2px;
    color: red;
}
```
is work!
