### ISSUE TITLE
Improperly unprefixing -webkit-box-orient when in a @supports block

### ISSUE THREAD

**Issue by blowery** [parcel-bundler/lightningcss#710]
v1.24.1 is now removing the `-webkit-` prefix from `-webkit-box-orient`. Compare the output from [v1.24.0](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40supports%20(%5Cn%20%20%20%20(display%3A%20-webkit-box)%20and%20(-webkit-box-orient%3A%20vertical)%20and%20(-webkit-line-clamp%3A%203)%5Cn%20%20)%20%7B%5Cn%20%20.foo%20%7B%5Cn%20%20%20%20display%3A%20-webkit-box%3B%5Cn%20%20-webkit-box-orient%3A%20vertical%3B%5Cn%20%20-webkit-line-clamp%3A%203%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.24.0%22%7D) to [1.24.1](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40supports%20(%5Cn%20%20%20%20(display%3A%20-webkit-box)%20and%20(-webkit-box-orient%3A%20vertical)%20and%20(-webkit-line-clamp%3A%203)%5Cn%20%20)%20%7B%5Cn%20%20.foo%20%7B%5Cn%20%20%20%20display%3A%20-webkit-box%3B%5Cn%20%20-webkit-box-orient%3A%20vertical%3B%5Cn%20%20-webkit-line-clamp%3A%203%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.24.1%22%7D).

## Input
```css
@supports (
    (display: -webkit-box) and (-webkit-box-orient: vertical) and (-webkit-line-clamp: 3)
  ) {
  .foo {
    display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  }
}
```

## 1.24.0
```css
@supports (display: -webkit-box) and ((-webkit-box-orient: vertical)) and (-webkit-line-clamp: 3) {
  .foo {
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    display: -webkit-box;
  }
}
```

## 1.24.1
```css
@supports (display: -webkit-box) and (box-orient: vertical) and (-webkit-line-clamp: 3) {
  .foo {
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    display: -webkit-box;
  }
}
```
