### ISSUE TITLE
Variable Visitor RawValue Wrong Transform

### ISSUE THREAD

**Issue by vsn4ik** [parcel-bundler/lightningcss#723]
```js
import { transform } from 'lightningcss';

const res = transform({
  filename: 'test.css',
  minify: true,
  code: Buffer.from(`
    .foo {
      margin: var(--margin-y) 0; 
    }
  `),
  visitor: {
    Variable(variable) {
      return {
        raw: '30px'
      };
    }
  }
});

console.log(res.code.toString());
```

Expected:
```css
.foo{margin:30px 0}
```
  
Actual:
```css
.foo{margin:30px0}
```
