### ISSUE TITLE
How to implement the use of mixins in the Vite + Vanilla project?

### ISSUE THREAD

**Issue by PxrpGill** [parcel-bundler/lightningcss#758]
Hi all! I wanted to use LightningCSS as a preprocessor in my project. In the documentation, I don't quite understand how to add custom at rules (@mixin and @apply/@include) to a CSS file. Can you please describe in more detail what I should do to make this work?

What i want: 

```CSS
@mixin test {
    border: 100px solid red;
}

.header {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 76px;
    border-bottom: 1px solid var(--line-color);
    @apply test;
}
```
