### ISSUE TITLE
Warning when `:is()` contains pseudo-elements

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#760]
## input

```css
.foo:is(::before) {
  color: green;
}
```

## output

```css
.foo:is() {
  color: green;
}
```

## expected

Prints a warning:

**Pseudo-elements are not valid within the :is() selector.**

```css
.foo:is(::before) {
  color: green;
}
```

This is also not valid in CSS nesting, so you should print a warning when the same situation is encountered when nesting.

This is a clear departure from the traditional CSS preprocessor(SCSS/Less), and as CSS nesting becomes more widely implemented in browsers, more and more authors will be confused(see https://github.com/parcel-bundler/lightningcss/issues/352). So we should explicitly tell them that they can't write this way in browsers at the moment.
