### ISSUE TITLE
Allow `composes` inside `@layer`?

### ISSUE THREAD

**Issue by jeffijoe** [parcel-bundler/lightningcss#761]
When using `composes` inside a layer, LightningCSS returns an error stating that `composes` cannot be used inside nested selectors.

```css
@layer components {
  .foo {
    composes: bar from './other.module.css';
  }
}
```

Would it be possible to either allow this, or to configure LightningCSS to surround each module file with a configurable layer name?

**Comment by kizu** [comment]
I think the nesting selector error is correct here: what `composes` does: when exporting the class name from a CSS module, it adds the other name alongside it.

It does not pull up the composed styles or modify them in any way. Meaning: it does not make sense to compose something inside a layer, as that layer won't apply to the composed class name.

A workaround, in this case, would be:

```css
.foo {
  composes: bar from './other.module.css';
}

@layer components {
  .foo {
    /* All the layered styles */
  }
}
```

Which, while uglier, will be much less confusing, as it won't create a possible false expectation that a composed class name is something that would also be inside that layer.
