### ISSUE TITLE
[Bug] grid-template identifiers do not get transformed (with CSS modules) when var() is used

### ISSUE THREAD

**Issue by mkrause** [parcel-bundler/lightningcss#762]
See [Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Atrue%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.test%20%7B%5Cn%20%20grid-template%3A%20%5C%22test%5C%22%20var(--foo)%3B%5Cn%20%20grid-template%3A%20%5C%22test%5C%22%201fr%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D):

```css
.test {
  grid-template: "test" var(--foo);
  grid-template: "test" 1fr;
}
```

Results in:

```css
.EgL3uq_test {
  grid-template: "test" var(--foo);
  grid-template: "EgL3uq_test" 1fr;
}
```

Note how this works as expected when 1fr is specified as size, but when `var(--foo)` is specified the template area name is left as a global identifier "test". This makes it impossible to use `grid-template` with `var()`, because the `grid-area` identifier will still be transformed, preventing the area from being assigned.

**Comment by danhorvath** [comment]
I experienced the same thing (also with css modules), currently I'm relying on [css variables as a workaround](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Atrue%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.filterRow%20%7B%5Cn%20%20--filter-row--filter-grid-area%3A%20filter%3B%5Cn%20%20--filter-row--operator-grid-area%3A%20operator%3B%5Cn%20%20--filter-row--condition-grid-area%3A%20condition%3B%5Cn%5Cn%20%20grid-template-columns%3A%20%5Bvar(--filter-row--filter-grid-area)%5D%201fr%20%5Bvar(--filter-row--operator-grid-area)%5D%2032px%20%5Bvar(--filter-row--condition-grid-area)%5D%201fr%3B%5Cn%7D%5Cn%5Cn.filter%20%7B%5Cn%20%20grid-column%3A%20var(--filter-row--filter-grid-area)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).

Source:
```css
.filterRow {
  --filter-row--filter-grid-area: filter;
  --filter-row--operator-grid-area: operator;
  --filter-row--condition-grid-area: condition;

  grid-template-columns: [var(--filter-row--filter-grid-area)] 1fr [var(--filter-row--operator-grid-area)] var(--sizing-300) [var(--filter-row--condition-grid-area)] 1fr;
}

.filter {
  grid-column: var(--filter-row--filter-grid-area);
}
```

Output:
```css
.EgL3uq_filterRow {
  --filter-row--filter-grid-area: filter;
  --filter-row--operator-grid-area: operator;
  --filter-row--condition-grid-area: condition;
  grid-template-columns: [var(--filter-row--filter-grid-area) ] 1fr [var(--filter-row--operator-grid-area) ] var(--sizing-300) [var(--filter-row--condition-grid-area) ] 1fr;
}

.EgL3uq_filter {
  grid-column: var(--filter-row--filter-grid-area);
}
```

This works across files too, albeit stylelint and vscode report issues with the syntax.
