### ISSUE TITLE
Declaration blocks for unrecognized pseudo-elements are not merged

### ISSUE THREAD

**Issue by birtles** [parcel-bundler/lightningcss#774]
[Playground link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A5898240%2C%22firefox%22%3A6553600%2C%22safari%22%3A983040%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%3A%3A-webkit-inner-spin-button%20%7B%5Cn%20%20height%3A%20auto%3B%5Cn%7D%5Cn%3A%3A-webkit-outer-spin-button%20%7B%5Cn%20%20height%3A%20auto%3B%5Cn%7D%5Cn%3A%3Abefore%20%7B%5Cn%20%20height%3A%20auto%3B%5Cn%7D%5Cn%3A%3Aafter%20%7B%5Cn%20%20height%3A%20auto%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Input:

```css
::-webkit-inner-spin-button {
  height: auto;
}
::-webkit-outer-spin-button {
  height: auto;
}
```

Expected:

```css
::-webkit-inner-spin-button, ::-webkit-outer-spin-button {
  height: auto;
}
```

Actual:

```css
::-webkit-inner-spin-button {
  height: auto;
}

::-webkit-outer-spin-button {
  height: auto;
}
```

I only came across this because it looks like rspack's [SwcCssMinimizerRspackPlugin](https://www.rspack.dev/plugins/rspack/swc-css-minimizer-rspack-plugin) does this while the Lightning plugin does not.

I guess it's safe to merge declaration blocks whose selectors include unrecognized pseudo-elements but maybe it's not common enough to worry about? Just filing this for completeness. Feel free to close it.
