### ISSUE TITLE
:is() with a [] selector causes removal of is:()

### ISSUE THREAD

**Issue by mathieulesniak** [parcel-bundler/lightningcss#775]
[Playground link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.tab%20%7B%5Cn%20%20%26%3Ais(input%5Btype%3D%5C%22radio%5C%22%5D)%20%7B%5Cn%20%20%20%20display%3A%20none%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn.tab%20%7B%5Cn%20%20%26%3Ais(input)%20%7B%5Cn%20%20%20%20display%3Anone%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Input:
```css
.tab {
  &:is(input[type="radio"]) {
    display: none;
  }
}

.tab {
  &:is(input) {
    display:none
  }
}
```
Expected:
```css
.tab:is(input[type=radio]){display:none}.tab:is(input){display:none}
```

Actual:
```css
.tabinput[type=radio]{display:none}.tab:is(input){display:none}
```

When mixing `is:` with a selector containing `[]` the `:is(` is removed, as the closing parenthesis.
Came across this behaviour when implementing a tabbed navigation with DaisyUI ([repo tab code](https://github.com/saadeghi/daisyui/blob/master/src/components/unstyled/tab.css#L12C1-L21C4), [implementation](https://daisyui.com/components/tab/)) . Simplified the playground to show the bug, this is not the actual DaisyUI code.
