### ISSUE TITLE
Nesting selector always inserted

### ISSUE THREAD

**Issue by valtlai** [parcel-bundler/lightningcss#777]
LightningCSS always inserts the nesting selector `&` regardless of the browser support.

For example, the following (with a class selector):

```css
.top {
  .sub {
    --prop: value;
  }
}
```

outputs this:

```css
.top {
  & .sub {
    --prop: value;
  }
}
```

And the following (with a type (/ an element) selector):

```css
.top {
  sub {
    --prop: value;
  }
}
```

outputs:

```css
.top {
  & sub {
    --prop: value;
  }
}
```

The former case should never output `&`. The latter case should output `&` only if the target browsers don’t support bare leading type selectors in nesting.
