### ISSUE TITLE
Support named timeline ranges in @keyframes

### ISSUE THREAD

**Issue by grimsteel** [parcel-bundler/lightningcss#786]
Right now lightningcss just removes blocks with named animation timeline ranges:

```css
@keyframes test {
  entry 0% {
    opacity: 0;
  }
  entry 100% {
    opacity: 1;
  }
  exit 100% {
    opacity: 0;
  }
}
```

[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40keyframes%20test%20%7B%5Cn%20%20entry%200%25%20%7B%5Cn%20%20%20%20opacity%3A%200%3B%5Cn%20%20%7D%5Cn%20%20entry%20100%25%20%7B%5Cn%20%20%20%20opacity%3A%201%3B%5Cn%20%20%7D%5Cn%20%20exit%20100%25%20%7B%5Cn%20%20%20%20opacity%3A%200%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) | [MDN reference](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes#values)
