### ISSUE TITLE
`exclude` option does not work as expected

### ISSUE THREAD

**Issue by chenjiahan** [parcel-bundler/lightningcss#792]
I'm using the `exclude` option of Lightning CSS. According to the documentation:

> The include and exclude options allow you to explicitly turn on or off certain features.

Adding `MediaRangeSyntax` to `exclude` turns out not to work:

![image](https://github.com/user-attachments/assets/2bb65813-8561-4ce0-9ed4-a681645b0d42)

> [playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A3473408%7D%2C%22include%22%3A0%2C%22exclude%22%3A128%2C%22source%22%3A%22%40media%20(min-resolution%3A%202dppx)%20%7B%5Cn%20%20.a%20%7B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

- input:

```css
@media (min-resolution: 2dppx) {
  .a {
    color: green;
  }
}
```

- current output:

```css
@media (resolution>=2dppx){.a{color:green}}
```

- expected output:

```css
@media (min-resolution: 2dppx){.a{color:green}}
```
