### ISSUE TITLE
Nesting in Svelte/Vite throws error

### ISSUE THREAD

**Issue by mattpilott** [parcel-bundler/lightningcss#810]
I must be doing something wrong but using nesting syntax is not working.

This works:
```css
.foo {
  color: red;
  
  & .bar {
    color: blue;
  }
}
```
But this does not:
```css
.foo {
  color: red;
  
  .bar {
    color: blue;
  }
}
```
I can't see why this would be the case.

Here's a repro https://stackblitz.com/edit/sveltejs-kit-template-default-lgagqb?file=src%2Froutes%2F%2Bpage.svelte
