### ISSUE TITLE
`light-dark` is broken when children have different `color-scheme`'s

### ISSUE THREAD

**Issue by foxt** [parcel-bundler/lightningcss#821]
If you take the following HTML
```html
<p>This text should have a black background</p>
```

And apply the following CSS:
```css
:root {
  --background: light-dark(white, black);
  --text: light-dark(black, white);
}

p {
  color: var(--text);
  background: var(--background);
  color-scheme: dark;
}
```

The text changes to white text on black background, as expected because `color-scheme` is set to `dark`.

However, change this to the transpiled CSS generated by lightningcss
```css
:root{--background:var(--lightningcss-light,#fff)var(--lightningcss-dark,#000);--text:var(--lightningcss-light,#000)var(--lightningcss-dark,#fff)}p{color:var(--text);background:var(--background);--lightningcss-light: ;--lightningcss-dark:initial;color-scheme:dark}
```
And the text is black on white. I believe this is because the polyfill uses css variables which do not recompute if child elements change any of the input variables, where as `light-dark` seems to do. You currently need to re-apply the `:root` theme variables on every element that changes `color-scheme`

**Comment by Hysterelius** [comment]
I have a similar problem, when I use this rust code:
```rust
use lightningcss::{
    printer::PrinterOptions,
    stylesheet::{MinifyOptions, ParserOptions, StyleSheet},
    targets::Browsers,
};

const STYLESHEET: &str = r#"
html {
  color-scheme: light dark;
}

html[data-theme=light] {
  color-scheme: light;
}

html[data-theme=dark] {
  color-scheme: dark;
}

button {
  background: light-dark(#aaa, #444);
}

"#;

fn main() {
    let mut stylesheet = StyleSheet::parse(STYLESHEET, ParserOptions::default()).unwrap();

    let _ = stylesheet.minify(MinifyOptions::default());

    let result = stylesheet
        .to_css(PrinterOptions {
            targets: Browsers {
                chrome: Some(96 << 16),
                ..Browsers::default()
            }
            .into(),
            ..Default::default()
        })
        .unwrap();

    println!("{}", result.code);
}
```

(which is the same as the [docs](https://lightningcss.dev/transpilation.html#light-dark()-color-function))

It incorrectly transpiles into:
```css
html {
  color-scheme: light dark;
}

html[data-theme="light"] {
  color-scheme: light;
}

html[data-theme="dark"] {
  color-scheme: dark;
}

button {
  background: var(--lightningcss-light, #aaa) var(--lightningcss-dark, #444);
}
```
Which is invalid css (and also doesn't match the docs' code), as it doesn't ever define the variables.

**Comment by MoritzLost** [comment]
I also just ran into this problem. Took a while to track down. Kind of surprising that a bug that completely breaks standard CSS has not been acknowledged or fixed for close to two years. Why has this feature not been turned off yet _by default_ if it can't be implemented in a way that doesn't break my CSS?

The default settings of a transpiler should only perform changes that are completely safe and don't break the CSS, in my opinion. If this can't be fixed, the `light-dark()` compilation needs to be turned off by default.

**Comment by devongovett** [comment]
Removing it by default would be a breaking change. We should add a note to the docs about this edge case though. There's already one about needing to define color-scheme.

**Comment by shivan-s** [comment]
Encountered this.

The "work-around" is the be explicit with the `color-scheme`.

```css
:root {
	/* Removing color-scheme this will cause the build to break (i.e. no green) */
	color-scheme: light dark;
	--green-light: #00FF00;
	--green-dark: #00AA00;
	--green: light-dark(var(--green-light), var(--green-dark))
}
```
