### ISSUE TITLE
Don't resolve correctly relative paths in "@import url()"

### ISSUE THREAD

**Issue by SergeyKrasnolobov** [parcel-bundler/lightningcss#839]
relative paths does not resolve correctly in css when different dir's level

failed case

```css
// dir_1/index.css
@import url('../dir_2/b.css');

// dir_2/b.css
@font-face {
    font-family: 'Any font';
    src: url('./font.woff2') format('woff2');
}
```
```js
import { bundle } from 'lightningcss';
import fs from 'node:fs';

const rawCss = fs.readFileSync('./dir_1/index.css')

const res = bundle({
  filename: 'index.css',
  minify: true,
  code: Buffer.from(rawCss)
});

console.log(res.code.toString());
```
