### ISSUE TITLE
Custom css can not maintain single-quote using lightningcss

### ISSUE THREAD

**Issue by GiveMe-A-Name** [parcel-bundler/lightningcss#849]
The css code:
```css
h1 {
  user-select: none;
  color: v-bind('color ? "red": "green"');
}
```
After `lightningcss` transform, the custom css would be double-quoted first. 
The single-quoted can't be maintained.
```css
h1 {
  user-select: none;
  color: v-bind("color ? \"red\": \"green\"");
}
```

`v-bind("color ? \"red\": \"green\"")` would transform into `color: var(--7ba5bd90-color\ \?\ \\\"red\\\"\:\ \\\"green\\\");` by vue-loader. It's not expected.

[Example in Lightningcss playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22h1%20%7B%5Cn%20%20user-select%3A%20none%3B%5Cn%20%20color%3A%20v-bind('color%20%3F%20%5C%22red%5C%22%3A%20%5C%22green%5C%22')%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Reference issue: https://github.com/web-infra-dev/rsbuild/issues/3595#issuecomment-2421679239
