### ISSUE TITLE
Support for Cascade Layers transpilation

### ISSUE THREAD

**Issue by pleunv** [parcel-bundler/lightningcss#856]
I can't seem to find it in the docs anywhere so I'm assuming that an equivalent of PostCSS's [Cascade Layers plugin](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-cascade-layers) is currently not supported. Is this something Lightning CSS would be willing to support? Given that tools such as Panda CSS are going all in on layers means that you're currently stuck with PostCSS in your pipeline if you need to support browsers `< Chromium 99`.

**Comment by fregante** [comment]
Is that even possible? The most it could do is to simply drop the extra syntax, but doing so would break the output.

## Input

```css
@layer module, state;

@layer state {
  .alert {
    background-color: red;
  }
}

@layer module {
  .alert {
    background-color: white;
  }
}
```

`.alert` is now `red`

## Output

```css
.alert {
  background-color: red;
}

.alert {
  background-color: white;
}
```

`.alert` is now `white`.

Since the layers may exist across files, you can't simply sort the rules in a file to achieve the same result.
