### ISSUE TITLE
Nested CSS adds extra `&` characters (that are not necessary?)

### ISSUE THREAD

**Issue by KeesCBakker** [parcel-bundler/lightningcss#862]
It looks like nested css adds extra `&` characters, which are not needed. I'm using NPM version `1.28.2` of the lightningcss package.

```js

const { transform } = require("lightningcss");

let css = `
.outer {
  color: red;
  .inner {
    color: blue;
  }
  .another-inner {
    color: black;
  }
}`;

let { code } = transform({
  code: Buffer.from(css),
  minify: true,
  sourceMap: false
});

console.log(code.toString());
```

This outputs:

```css
.outer{color:red;& .inner{color:#00f}& .another-inner{color:#000}}
```

When I prettify it, we'll get:

```css
.outer {
	color: red;

	& .inner {
		color: #00f
	}

	& .another-inner {
		color: #000
	}
}
```

Why are the `&`-characters added? I think they might not be needed.
