### ISSUE TITLE
`@keyframes :global()` selector not properly handled in CSS modules - Unexpected token Colon 

### ISSUE THREAD

**Issue by jantimon** [parcel-bundler/lightningcss#863]
When using the `:global()` selector with `@keyframes` the animation name cannot be parsed and LightningCSS throws a syntax error `Unexpected token Colon`

#### Example CSS
```css
@keyframes :global(foo) {
  to {
    opacity: 1
  }
}
```

#### Current Behavior

**`Unexpected token Colon`**

#### Expected Behavior
Same result as PostCSS ([Stackblitz Demo](https://stackblitz.com/edit/node-faevj5?file=index.js)):
```css
@keyframes foo {
  to {
    opacity: 1
  }
}
```
