### ISSUE TITLE
Media query range gap not calculated correctly

### ISSUE THREAD

**Issue by niksy** [parcel-bundler/lightningcss#864]
Consider the following CSS:

```css
@media screen and (width >= 1024px) {
  body {
    background: red;
  }
}
@media screen and (width < 1024px) {
  body {
    background: blue;
  }
}
```

What is expected here (when using syntax which is not syntax lowered to `min-width` and `max-width` equivalents) is that body will have blue background color on screen width less than 1024px, but anything equal or larger than that gets red background color.

Lightning CSS transforms this to following CSS ([playground](https://lightningcss.dev/playground/#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20screen%20and%20(width%20%3E%3D%201024px)%20%7B%5Cn%20%20body%20%7B%5Cn%20%20%20%20background%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%40media%20screen%20and%20(width%20%3C%201024px)%20%7B%5Cn%20%20body%20%7B%5Cn%20%20%20%20background%3A%20blue%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)):

```css
@media screen and (min-width: 1024px) {
  body {
    background: red;
  }
}

@media screen and (max-width: 1024px) {
  body {
    background: #00f;
  }
}
```

This results in blue background color even in 1024px screen width. Reshuffling ranges so that "lower than" is above is one solution but that can result in specificity bugs and is not quite advisable in any non-trivial codebase.

What I noticed is that this happens on values larger than 1000px, anything lower than that produces valid code. This is even covered in [test case](https://github.com/parcel-bundler/lightningcss/blob/9b2e8bbe732d7c101272ddab03ac21b88bf55c4a/src/media_query.rs#L1820).

Same query gets properly transformed with "value gap" using PostCSS and syntax lowering plugin ([playground](https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTQwbWVkaWElMjBzY3JlZW4lMjBhbmQlMjAod2lkdGglMjAlM0UlM0QlMjAxMDI0cHgpJTIwJTdCJTVDbiUyMCUyMGJvZHklMjAlN0IlNUNuJTIwJTIwJTIwJTIwYmFja2dyb3VuZCUzQSUyMHJlZCUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU0MG1lZGlhJTIwc2NyZWVuJTIwYW5kJTIwKHdpZHRoJTIwJTNDJTIwMTAyNHB4KSUyMCU3QiU1Q24lMjAlMjBib2R5JTIwJTdCJTVDbiUyMCUyMCUyMCUyMGJhY2tncm91bmQlM0ElMjBibHVlJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlMkMlMjJjb25maWclMjIlM0ElN0IlMjJicm93c2VycyUyMiUzQSU1QiUyMmNocm9tZSUyMCUzRSUzRCUyMDk1JTIyJTVEJTJDJTIybWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyUyMiUzQTAlMkMlMjJzdGFnZSUyMiUzQTIlMkMlMjJsb2dpY2FsJTIyJTNBJTdCJTIyaW5saW5lRGlyZWN0aW9uJTIyJTNBJTIybGVmdC10by1yaWdodCUyMiUyQyUyMmJsb2NrRGlyZWN0aW9uJTIyJTNBJTIydG9wLXRvLWJvdHRvbSUyMiU3RCU3RCU3RA==)).

If I’m understanding correctly, this is covered with [steps](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-media-minmax/src/transform-single-pair.ts#L47-L53) depending on which range identifier is requested.

This is known as [double breakpoint bug](https://tzi.fr/css/prevent-double-breakpoint/) and is common issue if codebase contains ranges which overlap. The issue gets even more complex when using values other than pixels since calculations are slightly different.

**Comment by fregante** [comment]
In the past I resolved this by using `not`

```css
@media screen and (width < 1024px)
```

becomes

```css
@media screen and not (min-width: 1024px)
```

This is an exact boolean equivalent and does not rely on rounding/steps.

**Comment by niksy** [comment]
Interesting, haven’t thought about that, but since rounding/steps approach is already implemented and known as a solution, maybe still go with this?

I’m wondering what could be the reason why this doesn’t work with values larger than 1000px. I don’t see anyhing related to this, maybe it’s that calculations on Rust side work differently?

**Comment by devongovett** [comment]
Thanks for the suggestion, @fregante! The above commit implements this. The input in the original issue now compiles to:

```css
@media screen and (min-width: 1024px) {
  body {
    background: red;
  }
}

@media screen and not (min-width: 1024px) {
  body {
    background: #00f;
  }
}
```
