### ISSUE TITLE
`list-style-type` overwrites `list-type`

### ISSUE THREAD

**Issue by philipp-spiess** [parcel-bundler/lightningcss#867]
We received a Tailwind CSS [bug report](https://github.com/tailwindlabs/tailwindcss/discussions/15368) about an unexpected conversoin of the `list-style-type` property:

```css
/* input.css */ 
.foo {
  list-style: inside;
  list-style-type: disc;
}
```

```css
/* output.css */
.foo {
  list-style: disc;
}
```

[Link to repro](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%5Cn.foo%20%7B%5Cn%20%20list-style%3A%20inside%3B%5Cn%20%20list-style-type%3A%20disc%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
