### ISSUE TITLE
[bug] :deep Compilation error

### ISSUE THREAD

**Issue by lzxb** [parcel-bundler/lightningcss#871]
Less source code
```less
.faq-desc :deep(.ui-collapse) {
  &-item-content {
    border-bottom-width: 0;
  }
}
```
Compile into CSS
```css
.faq-desc :deep(.ui-collapse) {
  border-bottom-width: 0;
}
.faq-desc :deep(.ui-collapse)-item-content {
  border-bottom-width: 0;
}
```
Will report an error，in `"lightningcss": "^1.28.2",`
```js
import { transform } from 'lightningcss';

transform({
  filename: 'style.css',
  code: Buffer.from(`
.faq-desc :deep(.ui-collapse) {
  border-bottom-width: 0;
}
.faq-desc :deep(.ui-collapse)-item-content {
  border-bottom-width: 0;
}

`),
  minify: true,
  sourceMap: true
});
```
