### ISSUE TITLE
`:nth-child(An+B of S)` selector does not transform class names

### ISSUE THREAD

**Issue by mkrause** [parcel-bundler/lightningcss#883]
Example:

```css
/* Here, .foo gets transformed */
.foo {
  color: red;
}

/* Here, .foo does not get transformed */
:nth-child(1 of .foo) {
  color: red;
}
```

With CSS Modules enabled, this outputs:

```css
.EgL3uq_foo {
  color: red;
}

:nth-child(1 of .foo) {
  color: red;
}
```

[(Playground link)](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Atrue%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%2F*%20Here%2C%20.foo%20gets%20transformed%20*%2F%5Cn.foo%20%7B%5Cn%20%20color%3A%20red%3B%5Cn%7D%5Cn%5Cn%2F*%20Here%2C%20.foo%20does%20not%20get%20transformed%20*%2F%5Cn%3Anth-child(1%20of%20.foo)%20%7B%5Cn%20%20color%3A%20red%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Note that the `.foo` selector remains untransformed in the input. I would expect it to get transformed to `.EgL3uq_foo`. Note that the `:nth-child(An+B of S)` syntax is now [well-supported by browsers as of 2023](https://caniuse.com/css-nth-child-of).
