### ISSUE TITLE
cssmodules-pure-no-check feature

### ISSUE THREAD

**Issue by jantimon** [parcel-bundler/lightningcss#889]
hi @devongovett 

would you be open to port the `cssmodules-pure-no-check` feature from [postcss](https://github.com/css-modules/postcss-modules-local-by-default?tab=readme-ov-file#pure-mode) to lightningcss?

The feature is a limited opt-out for the `cssModules: { pure: true }` linting rule similar to `@ts-ignore` or `@ts-nocheck`  or `eslint-disable` for **edge cases** in large projects where lightningcss is configured globally

For example:

```css
/** cssmodules-pure-no-check */

:global(#stripe-modal-backdrop) {
  background: rgba(0, 0, 0, 0.5);
}
```

In postcss the `/** cssmodules-pure-no-check */` disables the linting rule for the entire file.

If you are okay with porting the feature I would love to start working on a PR
