### ISSUE TITLE
Incorrect conversion from color-mix to oklab

### ISSUE THREAD

**Issue by ckoca** [parcel-bundler/lightningcss#899]
Lightning CSS performs the following conversion:

Input:

``` css
body {
  background: color-mix(in oklab, #101010 85%, transparent);
}
```

Output:

``` css
body {
  background: oklab(17.3042% --7.45058e-9 1.49012e-8 / .85);
}
```

It appears that the second argument of the `oklab` function is incorrect, as it includes a double negative sign.

You can observe this behavior in the [Lightning CSS playground](https://lightningcss.dev/playground/#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7274496%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22body%20%7B%5Cn%20%20background%3A%20color-mix(in%20oklab%2C%20%23101010%2085%25%2C%20transparent)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).
