### ISSUE TITLE
Minify - omit contents of invalid @media queries

### ISSUE THREAD

**Issue by pbowyer** [parcel-bundler/lightningcss#904]
I see CSS in the wild that has media queries that can never evaluate to `true`, e.g.:
```css
@media screen and (min-width: 1020px) and (max-width: 739px) {
  .foo {color: red}
}

@media screen and (min-width: 740px) and (max-width: 1019px) and (min-width: 1020px) and (max-width: 1135px) {
  .bar {color:green}
}
```

When minifying the CSS it would be good if lightningcss omitted these media queries and their contents entirely, resulting in a smaller bundle size.
