### ISSUE TITLE
:where(::before) and :where(::after) is compiled to :where()

### ISSUE THREAD

**Issue by petter** [parcel-bundler/lightningcss#906]
If you have style declarations for `:where(::before)` or `:where(::after)` they are just compiled to `:where()`. I would expect them to become `:where(::before)` and `:where(::after)` respectively.

[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%3Awhere(%3A%3Abefore)%20%7B%5Cn%20%20background-color%3A%20pink%3B%5Cn%7D%5Cn%5Cn%3Awhere(%3A%3Aafter)%20%7B%5Cn%20%20background-color%3A%20blue%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) demonstrating issue.

### Input
```css
:where(::before) {
  background-color: pink;
}
```

### Output
```css
:where() {
  background-color: pink;
}
```

### Input and output
```css
:where(::before) {
  background-color: pink;
}
```
