### ISSUE TITLE
Malformed @supports block when using combined :root, :host selectors

### ISSUE THREAD

**Issue by WillYallop** [parcel-bundler/lightningcss#907]
When transforming CSS that uses a combined `:root, :host` selector with modern colour formats (oklch/lab) and the targets set to anything greater that `last 3 versions`. The output includes a malformed and unnecessary `@supports` block.

## Reproduction

```js
import { transform, browserslistToTargets } from 'lightningcss';
import browserslist from "browserslist";

const code = Buffer.from(`:root, :host {
    --color-brand-background: oklch(100% 0 0);
}`);

const res = transform({
    filename: 'output.css',
    code: code,
    targets: browserslistToTargets(browserslist('last 4 versions'))
});

console.log(res.code.toString());
```

I've also reproduced this on the playground tool [here](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A0%2C%22firefox%22%3A0%2C%22safari%22%3A83886080%2C%22opera%22%3A0%2C%22edge%22%3A0%2C%22ie%22%3A0%2C%22ios_saf%22%3A83886080%2C%22android%22%3A0%2C%22samsung%22%3A0%7D%2C%22include%22%3A1113088%2C%22exclude%22%3A0%2C%22source%22%3A%22%5Cn%20%20%3Aroot%2C%20%3Ahost%20%7B%5Cn%20%20%20%20--color-brand-background%3A%20oklch(100%25%200%200)%3B%5Cn%20%20%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.29.1%22%7D).

## Current Output

```css
@supports (color: lab(0% 0 0)) {
   {
    --color-brand-background: lab(100% 0 0);
  }
}

:root {
  --color-brand-background: #fff;
}

@supports (color: lab(0% 0 0)) {
  :root {
    --color-brand-background: lab(100% 0 0);
  }
}

:host {
  --color-brand-background: #fff;
}

@supports (color: lab(0% 0 0)) {
  :host {
    --color-brand-background: lab(100% 0 0);
  }
}
```

The top `@supports` block is missing a selector, but also is not needed.

## Expected Output

```css
:root {
  --color-brand-background: #fff;
}

@supports (color: lab(0% 0 0)) {
  :root {
    --color-brand-background: lab(100% 0 0);
  }
}

:host {
  --color-brand-background: #fff;
}

@supports (color: lab(0% 0 0)) {
  :host {
    --color-brand-background: lab(100% 0 0);
  }
}
```

## Additional Context

- This only occurs when `targets` is set to support browsers older than `last 3 versions`.
- This is being executed with Node v22.13.1 and using Lightning version 1.29.1.
- I ran into this by running Lightning against the TailwindV4 output which uses the`:root, :host` selector.

Thanks in advanced for looking into this :)
