### ISSUE TITLE
linear-gradient `to` keyword conversion error

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#918]
## input

```css
.foo {
    background: linear-gradient(to right, red, green);
}
```

## output

[playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A1441792%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20%20%20background%3A%20linear-gradient(to%20right%2C%20red%2C%20green)%3B%5Cn%7D%5Cn%5Cn.bar%20%7B%5Cn%20%20background%3A%20linear-gradient(to%20top%20right%2C%20red%2C%20green)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

```css
.foo {
  background: -webkit-linear-gradient(right, red, green); /* The directions of the old and new grammars are not equivalent. */
  background: linear-gradient(to right, red, green);
}
```

## expected

```css
.foo {
  background: -webkit-linear-gradient(left, red, green);
  background: linear-gradient(to right, red, green);
}
```

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient#browser_compatibility

![Image](https://github.com/user-attachments/assets/ca12a7ad-c05f-4eb8-be6d-2c6f6470b3d6)
