### ISSUE TITLE
`calc(<LENGTH> - 0)` should be simplified to `<LENGTH>`

### ISSUE THREAD

**Issue by Jisu-Woniu** [parcel-bundler/lightningcss#928]
I encountered this code snippet in my CSS:

```css
.foo {
  margin: calc(100px - 0);
}
```

This should be simplified to:

```css
.foo{margin:100px}
```

[cssnano playground](https://cssnano.github.io/cssnano/playground/#eyJpbnB1dCI6Ii5mb28ge1xuICBtYXJnaW46IGNhbGMoMTAwcHggLSAwKTtcbn0iLCJjb25maWciOiJjc3NuYW5vLXByZXNldC1kZWZhdWx0In0=)

But Lightning CSS outputs:

```css
.foo{margin:calc(100px - 0)}
```

[Lightning CSS playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A8519680%2C%22firefox%22%3A8519680%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20margin%3A%20calc(100px%20-%200)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

A input of `0px` instead of `0` gives `.foo{margin:100px}` on both minifiers.

```css
.foo {
  margin: calc(100px - 0px);
}
```

If this is an unsafe operation, let me know what the possible corner case is.
