### ISSUE TITLE
Nesting breaks at-rules

### ISSUE THREAD

**Issue by lubomirblazekcz** [parcel-bundler/lightningcss#941]
LightningCSS is nesting at-rules wrong and inserts additional `& { }` which doesn't work in all browsers. This doesn't work for starting-style for example.

[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A8847360%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20%40media%20not%20all%20and%20(max-width%3A%20140px)%20%7B%5Cn%20%20%20%20display%3A%20none%3B%5Cn%20%20%7D%5Cn%20%20%5Cn%20%20%26%3Aopen%20%7B%5Cn%20%20%20%20%20%20%20%20opacity%3A%201%3B%5Cn%20%20%20%20%20%20%20%20transform%3A%20scale(1)%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%40starting-style%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20opacity%3A%200%3B%5Cn%20%20%20%20%20%20%20%20%20%20transform%3A%20scale(0.95)%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by devongovett** [comment]
These are indeed unnecessary but they shouldn't break anything. These rules are inserted implicitly by the parser in the browser too. Looks like this is working: https://codepen.io/devongovett/pen/NPWmgBm What is broken for you?

**Comment by lubomirblazekcz** [comment]
I was playing around with the new customizable select, and came around this problem. I had following code generated by lightningcss. And the starting-style animation didn't work properly. My original code didn't have the `&`, so I've tried to remove it in the browser and it started working. Maybe this happens only in some nesting conditions? I was having similar issue previously with custom-media not working too in some cases when additional `&` was present, but I'm not sure if I can reproduce that anymore.

```css
.x-control {
    &:has(select:not([multiple])) {
        & select {
            cursor: var(--cursor-pointer, pointer);

            &, &::picker(select) {
                appearance: base-select;
            }

            &::picker-icon {
                display: none;
            }

            &::picker(select) {
                border-radius: var(--radius-sm);
                border: 1px solid var(--color-main-tertiary);
                background: var(--color-body-primary);
                margin-block: calc(var(--spacing) * 1);
                padding: calc(var(--spacing) * 1);
                gap: calc(var(--spacing) * 1);
                cursor: auto;
                transform-origin: top;
                scrollbar-width: thin;
                scrollbar-color: var(--color-main) var(--color-body-primary);
                will-change: transform, opacity;
                transition: opacity var(--default-transition-duration) var(--ease-in-out), transform var(--default-transition-duration) var(--ease-out), display var(--default-transition-duration) allow-discrete, overlay var(--default-transition-duration) allow-discrete;
                flex-direction: column;
                display: flex;
            }

            &:not(:open)::picker(select) {
                opacity: 0;
                display: revert;
                transform: scale(.9);
            }

            &:open::picker(select) {
                opacity: 1;
                transform: scale(1);

                @starting-style {
                    & {
                        opacity: 0;
                        transform: scale(.95);
                    }
                }
            }

            & option {
                padding: calc(var(--spacing) * 2);
                font-size: var(--text-sm);
                font-weight: var(--font-weight-semibold);
                border-radius: var(--radius-sm);
                cursor: pointer;
                transition: var(--transition-background);
                line-height: calc(1em + .125rem);

                &::checkmark {
                    display: none;
                }

                &:hover, &:focus-visible {
                    background-color: var(--color-body);
                }

                &:checked {
                    background: color-mix(in srgb, var(--color-primary) 10%, transparent);
                }
            }
        }
    }
}

```
