### ISSUE TITLE
@property with <ratio> returns bad value

### ISSUE THREAD

**Issue by kapouer** [parcel-bundler/lightningcss#952]
This
```css
@property --aspect-ratio {
  syntax: "<ratio>";
  initial-value: 1;
  inherits: true;
}
```

triggers an error with lightningcss 1.29.3.

**Comment by kapouer** [comment]
This too
```css
@property --legend-border-style {
  syntax: "<line-style>";
  initial-value: solid;
  inherits: true;
}
```

Sorry if i'm not more verbose, these seem self-explanatory, and are generated by sass [in charts.css](https://github.com/ChartsCSS/charts.css/blob/main/package.json)
