### ISSUE TITLE
bug: `@property` rules remain nested in selector when targeting Chrome ≥120

### ISSUE THREAD

**Issue by jantimon** [parcel-bundler/lightningcss#962]
We ran into this issue while working on `@property` support in next-yak. It was reported by a user migrating from emotion in [DigitecGalaxus/next-yak#325](https://github.com/DigitecGalaxus/next-yak/issues/325)

According to the CSS spec, `@property` rules must appear at the top level of a stylesheet. 

They must not be nested inside selectors.

LightningCSS currently handles this differently depending on Chrome version:

- For Chrome ≤119: `@property` rules are correctly hoisted to the root level [Playground Link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7798784%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.example%20%7B%5Cn%20%20%40property%20--angle%20%7B%5Cn%20%20%20%20syntax%3A%20'%3Cangle%3E'%3B%5Cn%20%20%20%20inherits%3A%20true%3B%5Cn%20%20%20%20initial-value%3A%200turn%3B%5Cn%20%20%7D%5Cn%5Cn%20%20color%3A%20red%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) ✅ works
- For Chrome ≥120: `@property` rules incorrectly stay nested in selectors [Playground Link](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7864320%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.example%20%7B%5Cn%20%20%40property%20--angle%20%7B%5Cn%20%20%20%20syntax%3A%20'%3Cangle%3E'%3B%5Cn%20%20%20%20inherits%3A%20true%3B%5Cn%20%20%20%20initial-value%3A%200turn%3B%5Cn%20%20%7D%5Cn%5Cn%20%20color%3A%20red%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D) ❌ broken

#### Reproduction

When a user writes:

```css
.example {
  @property --angle {
    syntax: '<angle>';
    inherits: true;
    initial-value: 0turn;
  }
  animation: spin 3s linear infinite;
}
```

**Output for Chrome ≤119 (correct):**
```css
@property --angle {
  syntax: '<angle>';
  inherits: true;
  initial-value: 0turn;
}

.example {
  animation: spin 3s linear infinite;
}
```

**Output for Chrome ≥120 (broken):**
```css
.example {
  @property --angle {
    syntax: '<angle>';
    inherits: true;
    initial-value: 0turn;
  }
  
  animation: spin 3s linear infinite;
}
```

@Mad-Kat found out that in LightningCSS the CSS nesting feature being automatically disabled when targeting Chrome ≥120

https://github.com/parcel-bundler/lightningcss/blob/6c465c123deb549dfb45fd3558f25dca0dbde0d6/src/compat.rs#L1395-L1410

## Expected Behavior

`@property` rules should always be hoisted to the root level, regardless of target Chrome version or nesting feature status. 

In Chrome's actual implementation, `@property` rules don't work when nested inside selectors (as seen in [this CodePen example](https://codepen.io/jantimon-the-sans/pen/QwwwVBm)). 

**This means that LightningCSS generates broken CSS**

If you briefly outline how this issue should be solved we can create a pull request
