### ISSUE TITLE
`@mixin` example from documentation breaks property ordering

### ISSUE THREAD

**Issue by altano** [parcel-bundler/lightningcss#964]
The `@mixin` example [from the documentation](https://lightningcss.dev/transforms.html#custom-at-rules) doesn't seem to work right. It will add in the properties, but in seemingly random positions. I would expect them to be placed at exactly where the `apply` call is. 

The playground doesn't support plugins, so I can't provide a repro, sorry:

My vite config (my Astro config, technically) is:
```js
let mixins = new Map();

// ...

{
  // ...
  vite: {
    // ...
    css: {
      transformer: "lightningcss",
      lightningcss: {
        targets: browserslistToTargets(
          browserslist(">= 0.25% and last 1 year and not dead"),
        ),
        drafts: {
          customMedia: true,
        },
        customAtRules: {
          mixin: {
            prelude: "<custom-ident>",
            body: "style-block",
          },
          apply: {
            prelude: "<custom-ident>",
          },
        },
        visitor: {
          Rule: {
            custom: {
              mixin(rule) {
                mixins.set(rule.prelude.value, rule.body.value);
                return [];
              },
              apply(rule) {
                return mixins.get(rule.prelude.value);
              },
            },
          },
        },
      },
    },
    build: {
      cssMinify: "lightningcss",
    },
  },
```

My mixin definition is:
```css
@mixin card {
  background: var(--bg-card);
  border-radius: var(--border-radius-md);
  padding: var(--spacing-5);
}
```

My css that applies it is:
```css
      & :global(blockquote) {
        @apply card;

        transition: background var(--durations-color-scheme);
        margin-block-end: 0;
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
        border-left-width: 5px;
        border-left-color: var(--color-gray-400);
      }
```

(the `:global()` syntax is for Astro, it's not a typo. I made sure the issue repro'd without it fwiw)

here's the generated stylesheet:
```css
  article[data-astro-cid-ligjhper] blockquote {
    transition: background var(--durations-color-scheme);
    border-left-width: 5px;
    border-left-color: var(--color-gray-400);
    background: var(--bg-card);  /* <==== from the mixin */
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    border-radius: var(--border-radius-md);  /* <==== from the mixin */
    padding: var(--spacing-5);  /* <==== from the mixin */
    margin-block-end: 0;
  }
```

You'll notice that it placed `border-radius` in a seemingly random spot, but more importantly, it was placed after `border-top-left-radius` and `border-bottom-left-radius`, overriding those properties.

The original properties, not from the mixin, also seem to have been re-ordered, but not in an unsafe way. I'm not sure if that's a bug.
