### ISSUE TITLE
Vendor prefixes may be duplicated if the value is a CSS variable

### ISSUE THREAD

**Issue by wongjn** [parcel-bundler/lightningcss#969]
[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20-webkit-mask-image%3A%20url(.%2Ffoo.svg)%3B%5Cn%20%20mask-image%3A%20url(.%2Ffoo.svg)%3B%5Cn%7D%5Cn%5Cn.bar%20%7B%5Cn%20%20-webkit-mask-image%3A%20var(--foo)%3B%5Cn%20%20mask-image%3A%20var(--foo)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Given this input:

```css
.foo {
  -webkit-mask-image: url(./foo.svg);
  mask-image: url(./foo.svg);
}

.bar {
  -webkit-mask-image: var(--foo);
  mask-image: var(--foo);
}
```

Expect output to be identical. However, actual output:

```css
.foo {
  -webkit-mask-image: url(./foo.svg);
  mask-image: url(./foo.svg);
}

.bar {
  -webkit-mask-image: var(--foo);
  -webkit-mask-image: var(--foo);
  mask-image: var(--foo);
}
```
