### ISSUE TITLE
Bug in ordering of nested `@layer`s

### ISSUE THREAD

**Issue by kirk-loretz-fsn** [parcel-bundler/lightningcss#974]
[Lightning CSS Playground](https://lightningcss.dev/playground#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7798784%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40layer%20one%2C%20one.a%2C%20one.b%3B%5Cn%5Cn%40layer%20one%20%7B%5Cn%20%20%40layer%20b%20%7B%5Cn%20%20%20%20.test1%20%7B%5Cn%20%20%20%20%20%20color%3A%20red%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40layer%20one.a%20%7B%5Cn%20%20.test1%20%7B%5Cn%20%20%20%20color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

```css
/* Input */
@layer one, one.a, one.b;

@layer one {
  @layer b {
    .test1 {
      color: red;
    }
  }
}

@layer one.a {
  .test1 {
    color: green;
  }
}
```

The output results in `@layer one.b` occurring first, even though `@layer one.a` is declared first.
```css
/* Actual output */
@layer one {
  @layer b {
    .test1 {
      color: red;
    }
  }
}

@layer one.a {
  .test1 {
    color: green;
  }
}

@layer one.b;
```

You can test against this HTML. The text should be `red`, but Lightning CSS's output results in the text being `green`.
```html
<div class="test1">Hello world!</div>
```
