### ISSUE TITLE
Minification error when using nesting

### ISSUE THREAD

**Issue by anwerso** [parcel-bundler/lightningcss#989]
[Example in playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20margin%3A%20auto%3B%5Cn%5Cn%20%20.test%20%26%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%20%20%5Cn%7D%5Cn%5Cn.bar%20%7B%5Cn%20%20%40media%20(width%20%3E%2010em)%20%7B%5Cn%20%20%20%20margin%3A%20auto%3B%5Cn%5Cn%20%20%20%20div%20%26%20%7B%5Cn%20%20%20%20%20%20color%3A%20red%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

# Input
```
.bar {
  @media (width > 10em) {
    margin: auto;

    div & {
      color: red;
    }
  }
}
```

# Output
```
.bar{@media (width>10em){margin:autodiv &{color:red}}}
```

Not sure what combination of nesting, media query and `&` leads to `margin:autodiv`...

**Comment by firefoxic** [comment]
I caught the same bug. And it seems to be related to the nested `@media`:

```css
/* INPUT */
test-nesting {
	@media (width >= 40em) {
		color: beige;
		&:hover {
			color: wheat;
		}
	}
}

/* OUTPUT */
test-nesting{@media (width>=40em){color:beige&:hover{color:wheat}}}
/*                         Semicolon removed ↑ */
```

Но без `@media` обработка корректна:

```css
/* INPUT */
test-nesting {
	color: beige;
	&:hover {
		color: wheat;
	}
}

/* OUTPUT */
test-nesting{color:beige;&:hover{color:wheat}}
/* Semicolon not removed ↑ */
```
