### ISSUE TITLE
Avoid injecting `:is` in `:not` if all the arguments are known to be supported

### ISSUE THREAD

**Issue by sapphi-red** [parcel-bundler/lightningcss#997]
```css
:not(a, block) {
  color: blue;
}
```
is transformed to
```css
:not(:-webkit-any(a, block)) {
  color: #00f;
}

:not(:-moz-any(a, block)) {
  color: #00f;
}

:not(:is(a, block)) {
  color: #00f;
}
```
([playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A5701632%2C%22firefox%22%3A5111808%2C%22safari%22%3A917504%2C%22edge%22%3A5767168%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%3Anot(a%2C%20block)%20%7B%5Cn%20%20color%3A%20blue%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)).
But this isn't needed because `a` and `block` are both valid for the browser range.
